### ISSUE TITLE
Blog: "Now View This" related content

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#10]
**Issue:** If a post leads with video content no asset is shown in the "Now View This" section. 

**Expected behaviour:** Poster frame of the video should display. Or, the visitor should be able to select an image.

**Actual behaviour:** No image displays.

**Comment by chrismplus** [comment]
![missing-image](https://user-images.githubusercontent.com/26731347/30145568-aa2dd0a2-93c4-11e7-8034-63dca8c968f3.jpg)

**Comment by rdunk** [comment]
This should be resolved in phase two, as all content types require a card image.

The only exception will be pages such as 'About' that have been manually added as related content, these will use the M+ Stories placeholder image as they do not require a card image.
