### ISSUE TITLE
Video tile tags: extend frame slightly

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#100]
Can we extend the video frame vertically slightly so there's a bit more space for the title/tags? 

The bottom of the tile could have more space dedicated to the gradient fade. 

![image](https://user-images.githubusercontent.com/26731347/32769178-c9a13c96-c955-11e7-835b-e82268560a0b.png)

**Comment by rdunk** [comment]
Yep, increased by 10% in c3975b2688147b41a7eab5360682eb3b1bf70b4c.
