### ISSUE TITLE
Quotes rendering incorrectly in quotation element

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#101]
I've since removed these and it's going in for review soon--but flagging as something that needs fixing. It only happens with curly quotes, “” as opposed to straight quotes "". 

**Front-end:**
![image](https://user-images.githubusercontent.com/26731347/32816380-5baed60a-c9f3-11e7-8015-058176b76012.png)

**Back-end:**
![image](https://user-images.githubusercontent.com/26731347/32816401-6fb23174-c9f3-11e7-8055-70f90af5099c.png)

**Comment by rdunk** [comment]
Sorry this one is still not resolved. We've been in touch with the font foundry about it, there's a mistake with the codepoints and the quote marks are the wrong way round in this weight. They should hopefully provide a fixed version soon. Will update as soon as we have more information.

**Comment by rdunk** [comment]
Update: We now have the bolder weight fixed, just waiting on the corresponding italics.

**Comment by rdunk** [comment]
This should be fixed now as we've switched to a different stylistic set. Please reopen if not.
