### ISSUE TITLE
Size of headers

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#103]
Can we bump up the size of the headers? In the journal, in particular, we think this would be helpful. 

**Headers:**
![image](https://user-images.githubusercontent.com/26731347/32823269-7736e718-ca17-11e7-9cb0-4d14c5b9eeb0.png)

**Comment by rdunk** [comment]
I've pushed this to the development app but won't push it into production until you've signed off as it will affect the live sections too.

<img width="838" alt="screen shot 2017-11-17 at 15 54 53" src="https://user-images.githubusercontent.com/8467307/32956072-b4b86186-cbaf-11e7-8a80-7a0a8f4387dc.png">

**Comment by chrismplus** [comment]
Hi @rdunk -- it works well on Podium -- but seems large on the About pages. As we want to keep this universal on the site can we try revising the header size down slightly? 

Looks good on mobile. 

![headers](https://user-images.githubusercontent.com/26731347/32998675-2c3c82d0-cdd8-11e7-9f9d-2df81bc094ba.jpg)

**Comment by rdunk** [comment]
We've had a bit more of a discussion about this and I think the most sensible solution is that we introduce some variation in header sizes.

I've noticed at the moment most subheadings in articles are set as H1 (in markdown: #), this is actually not ideal, usually only one H1 should is used per page. So adding in some variation will help authors create more SEO friendly pages anyway.

We would have the option for two header sizes. h2 (##) would be shown bold in the slightly larger font size, and h3 (###) and below would be shown bold in the body font size. We would suggest that h1 (#) be avoided, as pages will generally use that for the page title, but if these are accidently added they would use the same styling as h2s.

I would suggest to revisit the Contact page and use a layout like this:

![contact-m-stories](https://user-images.githubusercontent.com/8467307/33017645-0ec3e5e6-cdeb-11e7-8d88-ed50d779eac1.png)

- **Contact** is **h1** (#).
- **Online** and **In Person** are **h2** (##).
- **Email Us**, **Follow us on Social Media**, **Visit M+ on the Web** and **Visit M+ in Hong Kong** are **h3** (###).

This should also give you a bit more flexibility in heading sizes for other sections.

Let me know how that sounds or if anything needs clarification.

**Comment by chrismplus** [comment]
Hi @rdunk -- this sounds good. Let's implement this.

**Comment by rdunk** [comment]
All done in 7dc91535604007de7cfa674d50fad28e7ab6dd52. Also pushed to production.
