### ISSUE TITLE
Unable to translate channels-php.json

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#106]
Unable to edit this section under languages:
![image](https://user-images.githubusercontent.com/26731347/32824090-8a8d5272-ca1a-11e7-9e9b-f3d3ab20d6db.png)

Receive the following error:
![image](https://user-images.githubusercontent.com/26731347/32824077-74be14c2-ca1a-11e7-87a1-f1614613a84f.png)

**Comment by rdunk** [comment]
Fixed, was due to Channels being renamed to Channel. Thanks for finding.
