### ISSUE TITLE
Chinese fullstops 。。。

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#107]
Hi @rdunk -- can we update the English full stops with Chinese ones in the context below? 

![search-full-stop](https://user-images.githubusercontent.com/26731347/32826276-bf179680-ca22-11e7-8bee-8c4a9d9eab8e.jpg)

**Comment by rdunk** [comment]
Fixed in 1f970d4eb470dc33d4736508f50bbe699389a2bd.

Full stops are no longer hard coded and are included as part of the translation here.
