### ISSUE TITLE
"Search" nav bar text

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#108]
I think this might have to do with the static menu that's currently in place--but I'm unable to view a Chinese language version of 'Search' at the moment. I've added in a translation under the 'Endpoints' in the CMS. 

Unable to update 'Search' translation:
![search](https://user-images.githubusercontent.com/26731347/32826918-43e2941c-ca25-11e7-9a8d-11b9a05e6bc7.jpg)

**Comment by rdunk** [comment]
Done! a43aa77f76b036f435d060475e3aa6753e9309e5
