### ISSUE TITLE
Unable to find translation fields

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#109]
Hi @rdunk -- I'm unable to find the following terms in the language documents: 
![image](https://user-images.githubusercontent.com/26731347/32829585-718304c6-ca2d-11e7-860b-703e9cc4a14c.png)

**URL:** https://plus.zakgroup.co.uk/tc/explore

**Comment by rdunk** [comment]
These were indeed missing from the translation files. Should be available now.
