### ISSUE TITLE
Blog: unexpected loading state

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#11]
**Issue:** There's an unexpected spacing issue on mobile when you first load M+ Stories. Please refer to attached photo. 

**Expected behaviour:** Blog post should align directly beneath the Newsletter module.

![img_7527](https://user-images.githubusercontent.com/26731347/30145499-36e5d7a2-93c4-11e7-81b2-b79ceead23b5.PNG)

**Comment by rdunk** [comment]
Closing as this seems to be fixed in phase 2. Please reopen if problem persists.
