### ISSUE TITLE
"Interactives" banner display

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#110]
Interactives banners aren't displaying their associated tags. 

CMS view: 
![image](https://user-images.githubusercontent.com/26731347/32830385-f351eefc-ca2f-11e7-9cf4-80ebfbda881c.png)

Front-end: 
![image](https://user-images.githubusercontent.com/26731347/32830398-05ee96fa-ca30-11e7-8e9b-c2e81e40baee.png)

**Comment by rdunk** [comment]
Thanks. Fixed in the CMS repo.
