### ISSUE TITLE
Explore: text search and emojis

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#111]
Can we find a way of linking text searches with emojis? The current structure is very much geared towards text and not easily returning emoji results, despite this being a key way to exploring.

**Comment by rdunk** [comment]
Could you elaborate a little on this one? Do you mean implementing similar functionality to the backend when searching for emojis i.e. searching both title and name fields?

**Comment by chrismplus** [comment]
The use-case would be a text search for 'popcorn' would surface the popcorn emoji. 

We'd need to find a way to ensure that this works with Chinese text searches too. This might mean adding the translation into the name of the emoji tag?

**Comment by rdunk** [comment]
Implemented in 2063809defa8fb4dd21e77ca4a4d8b41c6bf3658. There is now an new field for defining extra search terms for tags.

**Comment by chrismplus** [comment]
Thanks, @rdunk -- works well. We'll apply the text to the emojis next week when we have some more time.
