### ISSUE TITLE
Bibilography Formatting

### ISSUE THREAD

**Issue by rdunk** [mplusmuseum/mplusmuseum-stories#112]
I've noticed there are a few articles containing bibliographies which wrap text in `<small>` tags in order to achieve a smaller font size.

You may have noticed a warning when saving these pages. `<small>` tags are inline elements and should technically not wrap any block elements like headings `<h1>` or paragraph `<p>` tags.

Markdown doesn't support specifying font sizes for paragraph text, so do we need to introduce a dedicated block type for smaller text? Alternatively we could add an option to existing text blocks so they could be set to display text using a smaller font size.

**Comment by chrismplus** [comment]
Hi @rdunk -- yes good spot. I like the idea of adding this option to existing text blocks so we don't have an overabundance of content blocks.

**Comment by chrismplus** [comment]
Great thanks. @ellenoredsson -- FYI for future reference.
