### ISSUE TITLE
Tags linking back to 'Explore'

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#113]
****Update: if you refresh the homepage and click the 'building' emoji from the second banner image, "What’s Going on at the M+ Construction Site? November 2017", you should be able to replicate results.** 

Hi @rdunk -- one issue I've noticed (and I can't find a reliable means to replicate this, it seemingly happens at random) is that when I activate a tag on the homepage, it takes me to the Explore page, but the tag I activated hasn't been selected... it loads: 

https://plus.zakgroup.co.uk/en/explore

instead of:

https://plus.zakgroup.co.uk/en/explore?tag=guangdong, for instance.

**Comment by rdunk** [comment]
Ah, I imagine this is happening only if clicking on a tag is the first time navigating to the Explore page since the last page refresh. Oversight on my part, will push a fix.

**Comment by rdunk** [comment]
Was as expected. Fixed in 6ff0792bdc9a4cfb19f5648b8883fbbd6840c30f.
