### ISSUE TITLE
Another URL not resolving

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#114]
As per email with Brightcove support--this link doesn't seem to resolve by email: 

https://plus.zakgroup.co.uk/en/channel/ho-fan-on-the-decisive-moment 

Seems like it a link with issue [#102](https://github.com/mplusmuseum/mplusmuseum-stories/issues/102)

**Comment by rdunk** [comment]
Looks like I provided that link before we changed from 'channels' to 'channel'. Your example above seems to resolve fine for me.

**Comment by chrismplus** [comment]
Strange. It's working for me now but it wasn't earlier...

**Comment by chrismplus** [comment]
Closing issue--will keep an eye on links...
