### ISSUE TITLE
Unexpected linking behaviour from 'Explore'

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#115]
When I was demonstrating the site today, I searched ‘Yang Fudong’ in the explore section, it returned a blog post result, but when I clicked on the post, it linked to an earlier blog post. I haven’t been able to replicate this issue. It appears to be a one-time thing. 

**Browser:** Version 62.0.3202.94 (Official Build) (64-bit)
**OS:** macOS High Sierra Version 10.13.1 (17B48) 

**Steps I went through:**

- Navigate to Explore
- Filter by 'People'
- Type 'Yang Fudong'
- Press enter
- Click on blog post
- Observe results

**Comment by rdunk** [comment]
Hm, not able to replicate so far, will investigate.

**Comment by chrismplus** [comment]
Moving to backlog for now. Will continue to keep an eye on things.

**Comment by chrismplus** [comment]
Closing this. Will reopen if necessary.
