### ISSUE TITLE
Salesforce: newsletter migration

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#116]
Will need to update the newsletter integration for District integration. 

CC: @ellenoredsson @rdunk 

Marking for "backburner". Details to follow.

**Comment by chrismplus** [comment]
Hi @rdunk, @zakkyes,

I've sent the technical specs to Franka. Marking this task as 'research' for now as I'll have to liaise with the District regarding timings, migration and training in Salesforce. Would be good to know the path forward and how long you think it might take from your perspective.

CS

**Comment by chrismplus** [comment]
Hi @rdunk, @zakkyes, 

Reprioritising this as the first task while I work out the AWS side of things. I've moved this to the top of the board. Let me know whether you have any questions. Salesforce doc has been sent previously to Franka. 

CS

**Comment by chrismplus** [comment]
Hi @rdunk — are we in a position to push this update to the production environment once we tick over into September? We're prepared to make the switch-over—I'll coordinate timings for things on my end—will you be able to let me know when you expect this final push can be made? 

Also, have the new newsletter translation file fields been made available in the production CMS? Just want to ensure we have translations ready if needed.

**Comment by rdunk** [comment]
Hey @chrismplus, sure thing, should all be ready to go tomorrow, would that work for you? Only thing I'm not clear on is if we will need some different credentials for connecting to the production instance of the subscription server, or if ICT need to alter the configuration on their end to make the transition.

**Comment by chrismplus** [comment]
Hi @rdunk — this sounds good. Let's aim for tomorrow. I'll email ICT about the credentials for connecting to the production instance of the subscription server

**Comment by chrismplus** [comment]
Hi @rdunk — information has been emailed across re: credentials for connecting to the production instance of the subscription server.

**Comment by rdunk** [comment]
Hey @chrismplus.

I deployed the changes necessary for the new subscription service which all went smoothly, but it seems the request to the mail server is timing out, think it's a firewall issue, will email you over details. We can give this another go tomorrow AM GMT.

**Comment by chrismplus** [comment]
Hi @micahwalter — I've left details on the Slack channel about this task — let me know whether you need anything from my end.

**Comment by chrismplus** [comment]
Hi @rdunk —quick update: it looks like we're making progress with the AWS side of things, hope to have some more information to-hand shortly.
