### ISSUE TITLE
URL behaviour on blog

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#117]
@rdunk -- we're experiencing some [strange issues](https://drive.google.com/file/d/1BVDesMuF5VwX5TtFSNd6GBwvfbrDjGU8/view?usp=sharing) with the URL behaviour within the blog section. 

All issues below were uncovered using the following browser, OS and machine:

- **Browser:** Version 62.0.3202.94 (Official Build) (64-bit)
- **OS:** macOS High Sierra Version 10.13.1 (17B48)
- **Machine:** MacBook Pro

## **Issue 1:**
Here is an instance, after clicking 'Continue Reading' on the [latest post](https://stories.mplus.org.hk/en/blog/ask-an-m-curator-about-ink-art-your-questions-answered-1), where the URL updates to the blog posted directly _before_ it, (note URL for Yang Fudong post, it _should_ be the ask a curator post): 
![url-on-blog](https://user-images.githubusercontent.com/26731347/32929144-e358324c-cb90-11e7-8754-c23ad0aeef8a.jpg)

**Steps to re-create:** 
- Go to: https://stories.mplus.org.hk/en/blog
- Click "Continue Reading" on the first blog post available. 
- Scroll down the post and observe URL behaviour. 

## **Issue 2:** 
The first collapsed post does not register a URL update, i.e. it does not append to stories.mplus.org.hk. This occurs only _after_ you've scrolled to the _second_ post. However, if you scroll to the second post, then scroll back towards the top of the page, the URL _does_ update to the correct link, in this case, https://stories.mplus.org.hk/en/blog/ask-an-m-curator-about-ink-art-your-questions-answered-1. 

**Steps to re-create:** 
- Go to: https://stories.mplus.org.hk/en/blog
- Scroll down the page past the first collapsed post to the second post in the blogroll.
- Observe URL behaviour. 
- Scroll back up to the top of the page from the second post. 
- Observe URL behaviour. 

## **Issue 3:**
Incorrect URL updates _within_ a post, see image below for example:
![url-on-blog-2](https://user-images.githubusercontent.com/26731347/32929405-bcc9f910-cb92-11e7-8e1a-cc0a88fddadc.jpg)

**Steps to re-create:** 
- Go to: https://stories.mplus.org.hk/en/blog
- Scroll down the page until you get to the bottom and click 'More Posts'.
- Once more posts have been loaded, click into "[A Chat Between the Curator and Interns Behind ‘Samson Young: Songs for Disaster Relief’](https://stories.mplus.org.hk/en/blog/a-chat-between-the-curator-and-interns-behind-samson-young-songs-for-disaster-relief)". 
- Slowly scroll down to the bottom of the post and observe URL behaviour. 

CC'ing @dianewang as this will affect analytics.

**Comment by chrismplus** [comment]
@rdunk -- a video reference has been uploaded onto our Google Drive too: https://drive.google.com/file/d/1BVDesMuF5VwX5TtFSNd6GBwvfbrDjGU8/view?usp=sharing

**Comment by rdunk** [comment]
Thanks for the extensive information you provided for this.

Issues 1 and 3 were a problem with the app not recalculating the correct starting points for the posts when the content was changing. I updated the method it uses to recalculate in this commit 39e8c1b23bee474479e6223af20c3ec1f377b6c0 and it seems to be fixed, so this has been pushed to production.

For Issue 2, that commit also fixes the first post URL not updating correctly, and I've also introduced a feature so that the 'top level' URL is restored when you scroll back past the first post.

I'm closing this issue as it seems to be resolved. Please reopen if you are still experiencing problems.
