### ISSUE TITLE
Should a search also include words in tags? 

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#119]
My feeling is that a search should also incorporate text in tags... I can't see a downside to this. Thoughts? 

A search for "neon signs" or "Christopher Doyle" doesn't return any results. This will become more relevant as we begin to commission more interactive works. 
![image](https://user-images.githubusercontent.com/26731347/32938824-6c35bc0c-cbb8-11e7-944a-a948240d6382.png)

**Comment by rdunk** [comment]
Sure, I've added this in. Search will take a  minor performance hit but it shouldn't be too noticeable.

**Comment by chrismplus** [comment]
Hi @rdunk -- this still isn't working for me. See the following search result: 

https://plus.zakgroup.co.uk/en/search?q=christopher%20doyle

"Christopher Doyle" should be returned on the Neon Signs interactive tile; https://plus.zakgroup.co.uk/en/explore?tag=christopher-doyle

**Comment by rdunk** [comment]
That's bizarre, apparently the latest CMS revision wasn't pushed to production. Should be working now.

**Comment by chrismplus** [comment]
Confirmed it's working now.
