### ISSUE TITLE
Side-by-side image attribution layout on mobile

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#120]
Hi @rdunk -- is there a way we can attribute images more elegantly in such situations when they're side-by-side on small screens? 

![side-by-side-image attribution](https://user-images.githubusercontent.com/26731347/32941150-cc36e53e-cbbf-11e7-9227-b143eff1fe05.PNG)

**Comment by rdunk** [comment]
Hmm, that's a tricky one. Not sure how to resolve apart from truncating the text.

For the time being I've pushed a commit 9a59800a52bf9b300262be9ea8e8513bab997426 so the text for captions displays slightly smaller on mobile.

**Comment by chrismplus** [comment]
Thanks. I think that makes a difference. I'll close this one for now.
