### ISSUE TITLE
Blog: title in nav bar when on unique blog

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#121]
When deep-linked into a specific blog page, i.e. https://stories.mplus.org.hk/en/blog/ask-an-m-curator-about-ink-art-your-questions-answered-1, the title of the blog is no longer appended to the section header as it is when viewing the site on the blogroll. 

Should it?

![image](https://user-images.githubusercontent.com/26731347/32977607-86962736-cc6b-11e7-966e-73c78c00d15d.png)

**Comment by chrismplus** [comment]
As discussed--when on a unique piece of content, the content's title won't be appended to its section, but the section header would be linkable (back to the relevant section). 

i.e. when at https://plus.zakgroup.co.uk/en/blog/whats-going-on-at-the-m-construction-site-november-2017, "Blog" would link back to the blog home.

**Comment by rdunk** [comment]
Implemented in e94460fb5ceca7f831925806afa55e5cfcc89256.

**Comment by chrismplus** [comment]
"Blog" on the page below should link back to the blog, not top-of-page? 

**Reference:**
https://stories.mplus.org.hk/en/blog/whats-going-on-at-the-m-construction-site-november-2017

**Comment by rdunk** [comment]
I held off pushing anything to production before launch, but will push this now if you'd prefer.

**Comment by chrismplus** [comment]
Can't we test this first on https://plus.zakgroup.co.uk/en/ ?

**Comment by rdunk** [comment]
Yep, the expected behaviour is implemented on the dev URL (https://plus.zakgroup.co.uk/en/blog/whats-going-on-at-the-m-construction-site-november-2017), the "Blog" title links to the Blog landing page.

**Comment by chrismplus** [comment]
Sometimes it doesn't always link to the landing page. The link above does, but the one I tested this morning, and just now with this link (https://stories.mplus.org.hk/en/blog/q-a-with-the-composer-who-curated-the-playlist-for-the-weight-of-lightness-ink-art-at-m) there's no response. You remain on the same page.

**Comment by rdunk** [comment]
Great, live in production now.
