### ISSUE TITLE
Homepage: manual sort of dynamically created lists (particularly "Recent")

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#123]
Hi @rdunk -- logging this one here for future publishing flexibility. 

This would be most relevant as it regards the 'Recent' list.

**Comment by chrismplus** [comment]
Hi @rdunk -- so from an authoring perspective what I always imagined was that a list could be populated dynamically, incorporating a logic, as with 'Recent' (i.e. it could run by itself and we could forget about it but it would still publish new things--we wouldn't have to worry about it). But then if we wanted to we could tweak the order of things within 'Recent'. 

So, it would start dynamically, but there would be a manual override. 'Manual' would have the last say.

I think the above scenario describes the use-case. What you describe with the recent content getting placed into a manually sortable list speaks to this same point, I think. It sounds like the same thing? 

Does this make sense? So, dynamic content population would drive the process and relax the resources we need dedicated to it, but on occasion when we want to make a change to the order, we can. A completely manual 'Recent' doesn't feel super sustainable long-term. There would be a lot of updates to be made every time something new is published.

**Comment by chrismplus** [comment]
@rdunk — discussed with @ellenoredsson: we're happy to reset the dynamic list when a new item is added without a checkbox. Let me know whether you have any additional thoughts? I think this solution is pretty simple and makes sense for our authoring flows.

**Comment by rdunk** [comment]
Okay this one is finally implemented. The logic is as follows:

- Whenever a blog post, journal article, journal issue, channel episode or interactive is set to be published and visible, the CMS will automatically use the logic we previously determined to populate the recent items list on the homepage.
- This list is now editable. You can rearrange, add or remove items via the CMS as with a manual list.
- The list will maintain this order until a new item is published and unhidden, at which point it will be overwritten.

**Comment by chrismplus** [comment]
@rdunk works well. Closing.

**Comment by rdunk** [comment]
The algorithm for laying out the grid is shortest column first (left-to-right if equal). After each item is added, it finds the shortest column and adds the next item to that, etc. This is to balance the columns and prevent awkwardly big spaces appearing—especially for grids with many items where the effect would be compounded. So in this case it looks to be functioning correctly.

**Comment by chrismplus** [comment]
OK, so this means that the order of the CMS list isn't always going to be reflected on the front-end?  I don't see a major problem with this—just want to confirm.

**Comment by rdunk** [comment]
Yep exactly, it should be pretty close to the specified order, but sometimes you may see a few items out of place. On mobile (i.e. one column) it should be exact.

**Comment by chrismplus** [comment]
OK noted. Closing issue.
