### ISSUE TITLE
Can't filter Search results by Journal article

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#125]
Blog posts, info pages and interactives are available, but not journal articles:
![image](https://user-images.githubusercontent.com/26731347/33057473-20d7af52-cec6-11e7-9ef5-acbbafd450b5.png)

**Comment by rdunk** [comment]
Ah, you can scroll through more options with the dropdown. Shall we try and make that more obvious somehow?

**Comment by chrismplus** [comment]
Ohhh... I completely missed that (but I have seen it previously). I think we should make it more obvious somehow.

**Comment by chrismplus** [comment]
I think this is the way to go. We wouldn't display the entire list because of screen-size issues? 

If we could prioritise the list it would be: 

1. Blog Posts
2. Podium Articles
3. Videos
4. Interactives
5. Information Pages

I think we can remove: 

1. Pages
2. Podium Issues (these don't seem to be returned regardless)

**Comment by rdunk** [comment]
> We wouldn't display the entire list because of screen-size issues?

Yes exactly.

Implemented in 6df42158098f70128b7b411b36924935aaae1847. We are seeing issues returned in search results, e.g. [search for visual culture](https://stories.mplus.org.hk/en/search?q=visual%20culture).

I've left the last two items in (at the end of the list, in the above order) as it made sense that all content types have a related filter. If you feel strongly that these should be removed please feel free to reopen!

**Comment by chrismplus** [comment]
OK. Will discuss with the team. The terms "Pages" and "Information" pages will need revisiting, I think.
