### ISSUE TITLE
Remove ampersand on Chinese language version of site

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#126]
An ampersand is being dynamically generated by the Issue module: 
![image](https://user-images.githubusercontent.com/26731347/33060564-9f8c7be0-ced3-11e7-97d6-4ab268381b4f.png)

It should be: 
由{author}、{author}及{author}撰稿

**Comment by rdunk** [comment]
Ah yes, we have to hardcode this one it's too complicated to define using the shortcodes. Should be updated now. I've checked with an issue containing three authors and it seems to follow the pattern you've described, but should probably double check with a Chinese speaker before closing!

**Comment by chrismplus** [comment]
Thanks, @rdunk -- this is perfect.
