### ISSUE TITLE
Search: filter result dropdowns should stack on mobile?

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#127]
"Sort by Newest" gets cut off. Makes the filtering experience a little difficult as the visitor has to zoom out. 

**Device:** iPhone 6
**Browser:** Chrome/Safari

![img-7841](https://user-images.githubusercontent.com/26731347/33107260-6134d2e0-cf71-11e7-8449-f4c49285fc2a.png)

**Comment by rdunk** [comment]
Good find! Fixed in 27be0c91f2000729f1a730e802a203a5fccebe26.

**Comment by chrismplus** [comment]
Looks good!
