### ISSUE TITLE
Podium: banner element/tile for Issue

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#128]
Hi @rdunk -- can we append the Issue number to the banner _and_ tile in the following two instances (ideally this would be dynamic): 

**Tile:**
![podium-tile-card](https://user-images.githubusercontent.com/26731347/33113479-8b90eea8-cf93-11e7-9a61-235747750a8c.jpg)

**Banner:** 
Can we also add the contributors to the banner element?
![podium-banner-card](https://user-images.githubusercontent.com/26731347/33113706-9318c14a-cf94-11e7-9748-aba325bfba41.jpg)

**Chinese syntax:**
Podium Issue {1}
博文集第{1}期

Not having the Issue number there is less than ideal when viewing the site in Chinese.

**Comment by rdunk** [comment]
Hi @chrismplus, almost ready to push this—it was a little tricky to implement. The implementation means I can easily add it for other sections too though (i.e. search results, suggested items), would this be preferable?

**Comment by rdunk** [comment]
Implemented in c546850b42905bbf92d986f3ff085e73230c06d9. Let me know if you want me to roll it back for search results.

**Comment by chrismplus** [comment]
@rdunk -- do you mean when Issues are returned through search results? I don't think Issues will surface easily in search results--they're not really being surfaced through searches at the moment. In ticket [#125](https://github.com/mplusmuseum/mplusmuseum-stories/issues/125) we actually discuss removing the Issue as a search filter.

**Comment by chrismplus** [comment]
Hi @rdunk -- noted the Issue number is appended to Podium Issue. This fixes the syntax issue we were facing with Chinese language page. As noted above in the ticket--is it also possible to include the contributors in the banner?

**Comment by rdunk** [comment]
Ah, I didn't see that one. Yep should be possible, can implement that today.

**Comment by rdunk** [comment]
Done a3e3ff2f83cef952c63a689c03ba0b3dfe4a9b72!
