### ISSUE TITLE
Minor: social media: share text

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#13]
Can we have an optional field where we author our own custom social media share text alongside the current method of drawing in the title?

**Comment by chrismplus** [comment]
Moving to 'Ready'.

**Comment by rdunk** [comment]
Implemented in 460a2100853e7c0ac25256723a50488e9f30d872, there is now a field under the SEO tab for overriding the default share text (page title).

**Comment by chrismplus** [comment]
Thanks, @rdunk — will test. 

@ellenoredsson @laramplus — custom share text has been implemented on the site.

**Comment by chrismplus** [comment]
@rdunk — to confirm this works only for Weibo and Twitter?

**Comment by chrismplus** [comment]
Hi @rdunk — seeking clarification on the above comment. Is custom social media share text Weibo and Twitter specific?

**Comment by rdunk** [comment]
You can edit the links manually in the CMS to pass text as a URL parameter with curly braces to pass in a URL `{location}` or text `{text}`.

I know Twitter supports passing text (i.e. the content of your Tweet), so the link is the following:

`https://twitter.com/share?text={title}&url={location}`

Where as I believe sharing content on Facebook usually just means sharing a link, so only the `{location}` is included, although I haven't used Facebook for several years so I'm only going off the documentation here. The link for that is currently:

`https://www.facebook.com/sharer/sharer.php?u={location}`

If there are some platforms that you know allow sharing text, let me know and I can try and find the relevant parameters for the sharing URLs.
