### ISSUE TITLE
Banner: image fallback solution

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#132]
Hi @rdunk -- as mentioned on Slack, can we enable the card image to act as a fallback? I think this would be preferable to having to upload another image... thoughts?

**Comment by chrismplus** [comment]
Hi @rdunk — if this has been implemented can we remove the banner image fallback upload option from the CMS?

**Comment by rdunk** [comment]
We can, but it is currently not required and just offers a bit more flexibility (where you may want a different banner fallback to the card image). Is the concern that it may be confusing for content editors?

**Comment by chrismplus** [comment]
Oh, I see. If I was authoring the page without knowing that I'd upload an image regardless. So this is in case it is different from a 'Card' image?
