### ISSUE TITLE
Mobile: issue with video banners

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#133]
**Video player becomes accessible depending on how you tap the image (not sure how to replicate this cleanly, tap around a bit):**
![img_7850](https://user-images.githubusercontent.com/26731347/33171478-2e8de8a6-d087-11e7-8c82-275a23f1fb70.PNG)

**Video is still accessible if you tap around:** 
![img_7851](https://user-images.githubusercontent.com/26731347/33171480-2ebff35a-d087-11e7-8875-a084ea723431.PNG)

I think on _mobile_ we should find a means to completely disable banner video elements.

**Comment by rdunk** [comment]
Agreed, these should ideally fallback to the poster images we recently implemented. Which device was this bug found on?

**Comment by chrismplus** [comment]
iPhone 6. They didn't load in this way--they loaded with the still image. But after swiping around the site it tried to load-in the video element. 

Also, I noticed now that video banners are also working on mobile. This wasn't happening previously, but I think it's actually preferable...

**Comment by rdunk** [comment]
I think this might been an iOS specific issue. Apple recently relaxed the rules a little bit so I pushed a change that added a property to the banner videos to try and force them to play on iOS, and it seems that it worked.

Lets keep this one open for now, sounds like it needs some more testing.

**Comment by chrismplus** [comment]
I haven't been able to replicate this issue since the fix has been pushed. Closing.
