### ISSUE TITLE
Minor: 404 page editing

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#134]
Can the 404 page be made more authorable in line with the other 'Pages', i.e. add images etc? 

CC: @ellenoredsson

**Comment by chrismplus** [comment]
@rdunk — as noted in our call, M+ will send you a template of what we're thinking for this. 

CC: @ellenoredsson

**Comment by chrismplus** [comment]
404 page structure:

![404-page-structure](https://user-images.githubusercontent.com/26731347/34704439-16abddd4-f534-11e7-8274-598bd4675256.jpg)

**Comment by rdunk** [comment]
ba1b7f33964922f34bdf61eb5be0d4488244525e adds support for custom 404 data. Should be self explanatory when editing the 404 page via the CMS. Let me know if you have any more questions.

**Comment by chrismplus** [comment]
Thanks @rdunk

**Comment by chrismplus** [comment]
@ellenoredsson 404 page ready for editing.
