### ISSUE TITLE
Summary Image: CMS SEO tab

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#135]
Hi @rdunk — as with #132, can we use the 'card' image dynamically for the Summary Image under the SEO tab? At the moment this is a manual upload. I think we can cut out a step here. 

A unique summary image in SEO tab. Let's draw-in the 'Card' image instead. 
![image](https://user-images.githubusercontent.com/26731347/33194987-d913b9d6-d10e-11e7-99fe-656d43687352.png)

**Comment by rdunk** [comment]
This should already be in place, if the summary image field is left blank and a card image exists, the CMS will use the card image for SEO/sharing purposes instead. I've updated the field description to the following to make this clearer for authors:

> Optional image used for SEO and sharing purposes. If this field is left blank and this page has a card image, the card image will be used in its place.
