### ISSUE TITLE
Channel: view error

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#136]
Clicking the 'View' button within an episode in the CMS produces an error. The URL is still trying to resolve under 'channels' as opposed to 'channel'. 

**Clicking 'View' returns a 404:** 
![channel-view-error](https://user-images.githubusercontent.com/26731347/33195406-1c00116a-d112-11e7-98ad-547694d3ef6a.jpg)

**Comment by rdunk** [comment]
Just fixed this. That URL is authorable in the CMS via the related template settings, but I'd recommend not editing those pages if at all possible. We shouldn't have to change this again regardless.

Tested working.
