### ISSUE TITLE
View More button

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#137]
Hi @rdunk — after clicking/tapping 'View More', can we maintain our current position on the window, instead of being dynamically taken down the page with the rest of the content behind the button? 

Thoughts? This seems to be the more natural result; it allows the visitor to scroll down from their current position, instead of losing their place and having to scroll up to view the new content. 

Thoughts? 

![view-more](https://user-images.githubusercontent.com/26731347/33198152-5fa164de-d124-11e7-9516-59699e98c1a8.jpg)

**Comment by rdunk** [comment]
Thanks for bringing this one up. It was not really ideal behaviour admittedly, but seemed to be the only way to do this with the layout library we are using.

I've spent the past few hours rewriting the layout functionality from scratch so we can remove the need for this third party library entirely, gives us a bit more flexibility and should fix this issue. Will leave this open for testing but seems to work nicely.

**Comment by chrismplus** [comment]
Thanks, @rdunk — this is a lot better.
