### ISSUE TITLE
Explore page: errant comma

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#138]
Hi @rdunk — I've noticed the comma highlighted below doesn't roll over onto a new line on mobile. Can we address this?

**Device:** iPhone6S
**Browser:** Chrome

![errant-comma](https://user-images.githubusercontent.com/26731347/33247535-ba12c020-d359-11e7-91c3-2974fa4fc470.jpg)

**Comment by rdunk** [comment]
Fixed in 1e880771776f0ba1beb427be1c6485e9ec65bc9f.
