### ISSUE TITLE
Search: results aren't returned

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#139]
I've noticed this more on mobile than on desktop. 

Sometimes, after clicking on a tag, it's associated content is not returned in the result. Steps to replicate are not consistent. 

**Device:** iPhone 6S
**Browser:** Chrome

A search for the family emoji—content is associated with the tag but is not displayed: 
![search-hidden-results](https://user-images.githubusercontent.com/26731347/33250640-af0b9c20-d36c-11e7-8614-894d58207b61.PNG)

**Comment by rdunk** [comment]
I believe this was related to #142 and should now be fixed.
