### ISSUE TITLE
Website: cookies

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#14]
**Use case:** I enter the English version of the website, but switch it to Chinese. I read an article and then close the browser. When I go back to M+ Stories, it brings up the page in English once more, not remembering that I set the site to Chinese. 

**Expected behaviour:** Stories should remember which language I viewed it on last. 

**Actual behaviour:** No cookie is set. The site doesn't remember my language preference.

**Comment by rdunk** [comment]
Added in phase 2.

The server will check first for any language preference stored in a cookie, and then fallback to browser preference.

Please note that obviously visiting any URL that starts with a language code (/en/ or /tc/) will override the stored preference.
