### ISSUE TITLE
Channel: linebreak for video credits

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#140]
Can we insert an extra linebreak above the 'Video Credits' module for responsive layout? At the moment there's no break for smaller devices—see the image below. 

**URL:** https://stories.mplus.org.hk/en/channel/ho-fan-on-the-decisive-moment
**Browser:** Chrome
**Devices:** all

![channel-linebreak](https://user-images.githubusercontent.com/26731347/33250776-92769c12-d36d-11e7-913b-8a0129f10a68.jpg)

**Comment by rdunk** [comment]
Implemented in d96b8f7c0ecb56674c80cc16145d7dac5f8e8910.
