### ISSUE TITLE
Homepage: 3 column layout

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#141]
Please see image below for unexpected behaviour regarding tile layout (refer to yellow highlights).

**Viewport:** 1440 x 760
**Browser:** Chrome Version 62.0.3202.94
**Device:** MacBook Pro (Retina, 13-inch)

**Expected behaviour:** tiles should display on the same line, not break to a new one. 

I'm wondering whether the new library might have something to do with the increased frequency of this issue?

![homepage-layout](https://user-images.githubusercontent.com/26731347/33250855-266c50a6-d36e-11e7-8012-144226cb82c9.jpg)

**Comment by rdunk** [comment]
Added some more checks in f3f18e9efae4194a0b5cd8b32ce0121e7de84bdf so there should no longer be unused columns. I'm now unable to replicate so closing, please reopen if the problem persists.
