### ISSUE TITLE
Returned tag search results: tiles expand full screen width

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#142]
A search for "🏗️📐" on the explore page returned tiles stretching the full-width of the screen. As with the other returned search issues, this is difficult to replicate with any regularity. It does seem to occur more often on my MacBook Pro than iMac. 

**Device:** MacBook Pro (Retina, 13-inch)
**Viewport:** 1440 x 760
**Browser:** Chrome 62.0.3202.94

![screencapture-stories-mplus-org-hk-en-explore-1511612870198 copy](https://user-images.githubusercontent.com/26731347/33250991-0e953b54-d36f-11e7-8ebc-13a4f8edc86b.jpg)

**Comment by rdunk** [comment]
I noticed this last night too, apologies, seems to have been introduced with the new layout method. Should be fixed in 5cfae36dbeb2bb7f3a76ee48ee789dbe832912c8.
