### ISSUE TITLE
Newsletter sign-up CTA options

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#143]
Can we have a CTA for the newsletter where the signup field is not hidden behind a click or a tap (see image below)? 

Furthermore, we had the following use-case last week: _when sending out an all-staff email to get people to subscribe to the newsletter, the easiest direction was to get them to click on the 'hand icon'._ 

Is there a way we can embed the newsletter signup onto a unique page, like a 'Basic Page'? This way there will be a unique URL we can send people to. Thoughts?

**Newsletter--unfurled:** 
![image](https://user-images.githubusercontent.com/26731347/33263824-3146093a-d3a6-11e7-8c77-a33e35b6e895.png)

**Comment by rdunk** [comment]
I can implement the CTA today, two options:

- The element is as it is now with the added ability to set a 'default' state. This would mean sign up input can be shown by default, but you would still be able to click the cross and go back—as in the current implementation.
- The sign up input is shown with no cross/option to 'go back'. In this case, do you need text above the input or will the title suffice as a descriptor?

In either case, should there be an option for a social media CTA too?

For the dedicated page, do you have an example of what this might look like, or what other content it may contain?

**Comment by chrismplus** [comment]
## CTA
@rdunk I think the first option offers the most flexibility. To confirm: 

- The element could be either state—the current display or the sign-up box shown by default. 
- If the sign-up box is on display only, the cross will take you back to the current layout. 

Yes, I think it does make sense for this option to also be available on for the social icons. 

## Dedicated page
My feeling is the most effective solution would be to enable newsletter sign-up modules on both forms of About page; basic and documentation. 

I think we could include it on both the current [About](https://stories.mplus.org.hk/en/about) and [Contact Us](https://stories.mplus.org.hk/en/contact-m-stories) pages for instance.

**Comment by chrismplus** [comment]
Hi @rdunk — we didn't go over this yesterday during our call but we can proceed with this after tasks relating to @micahwalter have been completed.

**Comment by chrismplus** [comment]
Hi @rdunk — can we prioritise this task?

**Comment by chrismplus** [comment]
@rdunk — could I get an update on this task? We're planning a social media push around this.

**Comment by rdunk** [comment]
Apologies for the delay on some of these, I can get this one built by end of day tomorrow.

**Comment by rdunk** [comment]
This has now been implemented for the homepage repeater in 1df4a67c6af3aab7358d3284be5a4c45fea3214f.

**Comment by chrismplus** [comment]
Thanks, @rdunk — works as expected. Closing issue.

**Comment by chrismplus** [comment]
Hi @rdunk — would you be able to provide an update on the dedicated page for newsletter sign-up? Thanks in advance. 

CC: @laramplus @ellenoredsson

**Comment by rdunk** [comment]
4c90ebd48b1d229277f78d6e07d96bc0af820430 adds support for "Newsletter Signup" content blocks. You can add these to pages as you would any other content block. So if you want to go ahead and create a dedicated newsletter page using the default layout that should be straightforward now.

The styling is inherited from the input fields you find on the homepage (i.e. white box with a shadow and blue button). Let me know if this works for you.
