### ISSUE TITLE
Minor: Safari: banner videos not displaying

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#144]
With the exception of the top banner, videos do not seem to play within banner elements further down the homepage when browsing the site on Safari. 

Listed as a 'bug', it's more 'unexpected behaviour', as the fallback is working and there doesn't seem to be any effect on functionality. 

**Browser:** Safari Version 11.0.1 (13604.3.5)
**Device:** MacBook Pro (Retina 13-inch)
**OS:** 10.13.1  
**URL:** https://stories.mplus.org.hk/en/

Banner video reverts to still-image backup (with the exception of the top element): 
![image](https://user-images.githubusercontent.com/26731347/33270404-ea8f2e7c-d3be-11e7-943b-9eccf9d678d9.png)

**Comment by rdunk** [comment]
This is apparently a 'feature' of Safari on High Sierra. The intention is to prevent video spam/adverts but obviously this negatively affects websites using videos as animated images, etc. Unfortunately not much we can do on this one.

**Comment by chrismplus** [comment]
Oh well. No worries—closing.
