### ISSUE TITLE
All items in content list not displaying after CTA button

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#145]
Note missing elements on the front-end display (only displays the first three items. 

This is the result of clicking the 'View More' button. Can't always be replicated. 

**List view in the CMS:** 
![content-list-issue](https://user-images.githubusercontent.com/26731347/33297641-2975b1ac-d41d-11e7-9b92-c6aba9508a7b.jpg)

**Front-end display:**
![image](https://user-images.githubusercontent.com/26731347/33297629-1cd9873e-d41d-11e7-9ade-d27c00846c02.png)

**Comment by rdunk** [comment]
I'm unable to replicate this, are there any steps I should take to try and reproduce?

**Comment by chrismplus** [comment]
Yes, as noted in the description it's hard to reproduce. It seemed to only occur in that window that coincided with the issues detailed in #142 and #139. Will close and keep an eye on it.
