### ISSUE TITLE
New issue: play button appearing on banner on mobile

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#146]
Hi @rdunk — this seems to have been recently introduced. When browsing the site incognito on Chrome, the play button is becoming viewable on banner elements that have a video associated with them. 

Might this have to do with the recently introduced Brightcove excerpt integration?

**Device:** iPhone 6S
**Browser:** Chrome

![img-7861](https://user-images.githubusercontent.com/26731347/33306185-5fee2e7e-d44c-11e7-98bc-58c1ca45557c.png)
![img-7862](https://user-images.githubusercontent.com/26731347/33306186-601a09ae-d44c-11e7-8447-46a653f964e0.png)

**Comment by rdunk** [comment]
Strange, I preemptively pushed commit 241ea571717a54a8dcef6ce1b135cedf607782a5 yesterday to hide these. This is what I'm seeing on iPhone 6S Safari/Chrome. Can you confirm this is still happening? Perhaps the latest version hadn't been pushed to production when you last checked..?

<img width="290" alt="screen shot 2017-11-28 at 13 42 43" src="https://user-images.githubusercontent.com/8467307/33323273-d646314c-d443-11e7-97a9-396b0a58adc0.png"><img width="290" alt="screen shot 2017-11-28 at 13 43 00" src="https://user-images.githubusercontent.com/8467307/33323271-d62d9dbc-d443-11e7-9c8e-0ba4aecd655d.png">


<img width="290" alt="screen shot 2017-11-28 at 13 47 26" src="https://user-images.githubusercontent.com/8467307/33323244-c066c134-d443-11e7-9eb3-942136c07eba.png"><img width="290" alt="screen shot 2017-11-28 at 13 47 48" src="https://user-images.githubusercontent.com/8467307/33323243-c0515d12-d443-11e7-9d83-e60ce4175f25.png">

**Comment by chrismplus** [comment]
I can't replicate it anymore. I'll reopen if necessary.
