### ISSUE TITLE
Implementing Google Tag Manager

### ISSUE THREAD

**Issue by dianewang** [mplusmuseum/mplusmuseum-stories#147]
Hi @rdunk,

I've recently discussed this with @chrismplus but I'm thinking about implementing Google Tag Manager and running GA through that instead. Would you have any flags about that process? 

If you're familiar with the process I'm happy to have you take lead, but I'm also open to coordinating the switch at the same time if needed. As we don't have any tags (that I know of) on our Google Analytics setup, I imagine the switch won't be too cumbersome.

I've set up a Google Tag Manager account for us at mplus.org.hk (since it tracks subdomains), and can share you on that and our Google Analytics for set up purposes. 

Let me know what you think!

**Comment by rdunk** [comment]
Hi @dianewang,

We're currently using a [third-party plugin](https://github.com/MatteoGabriele/vue-analytics) to handle the Google Analytics integration which does allow us quite a lot of flexibility in terms of [page tracking](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/page-tracking.md), [event tracking](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/event-tracking.md), [social interactions](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/social-interactions.md), etc.

At present there doesn't seem to be a satisfactory Google Tag Manager plugin available for the framework we have used to build the front-end, so we would most likely build a custom plugin for integrating Google Tag Manager. At the moment I believe we are using GA to track page views and also some specific events for when users expand and collapse a blog post. The specific blog events would need to be implemented through a GTM tag. I'm not sure how easy it will be to replicate the 'expand' and 'collapse' events, you may just have to switch over to a 'toggle' event, depends on how much flexibility GTM offers in terms of targeting elements/state.

The other consideration is that the website is built as a "single-page application", meaning GA will not automatically track page views. We would need to build some functionality into the GTM plugin to simulate page views that GA can pick up on. This shouldn't be too complicated though.

**Comment by rdunk** [comment]
Also, forgot to mention that access to the Stories GA panel/data could be useful to have whilst building this. If you're happy to share that let me know, if not we can run tests through an account of ours.

**Comment by dianewang** [comment]
Absolutely happy to share access to our GA panel - which email(s) should I send access to?

**Comment by chrismplus** [comment]
Captured as part of another parcel of work. Closing.
