### ISSUE TITLE
Question: Brightcove styling on mobile

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#148]
Hi @rdunk — 

re: Adrian's response from Brightcove Support

I can no longer replicate the inconsistent styling issue on desktop. I did want to check-in with you about mobile styling though. Mobile devices are rendering the play button in the following states: 

![brightcove-button-states](https://user-images.githubusercontent.com/26731347/33354729-35014aea-d4ef-11e7-8e69-98a4fd38fa8f.jpg)

Is this expected behaviour? I feel it should mirror the desktop styling? 

i.e. (screengrab from thin desktop window):
![image](https://user-images.githubusercontent.com/26731347/33354916-22499b7c-d4f0-11e7-8cfc-ca364e6a8ab0.png)

**Comment by rdunk** [comment]
I've replied directly to Brightcove support about this one.

**Comment by rdunk** [comment]
Fixed!

**Comment by chrismplus** [comment]
Brilliant!
