### ISSUE TITLE
Style guide

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#149]
Create style guide (see Bootstrap example: https://bootswatch.com/flatly/) so that we can reference current _M+ Stories_ styling to other projects. 

CC: @micahwalter @laramplus @dianewang

**Comment by rdunk** [comment]
Will begin work on this very shortly!

**Comment by rdunk** [comment]
This should be ready early next week.

**Comment by chrismplus** [comment]
Hi @rdunk — could you provide a quick update on this. Can you pass the style guide to @micahwalter before the end of the week?

**Comment by rdunk** [comment]
@micahwalter @chrismplus Style guide [available here](https://mplusmuseum-stories-styleguide-qrpwlczgcl.now.sh/). Let me know how you'd like to proceed with it.

**Comment by micahwalter** [comment]
@rdunk - This is great. Can you point me to the source/markup so I can share with dev team?

**Comment by rdunk** [comment]
Update for @chrismplus: Shared this with @micahwalter via our studio GitLab account.

**Comment by chrismplus** [comment]
@micahwalter — do you have everything you need with the style guide?

**Comment by micahwalter** [comment]
Yes, I think what we have is useful at this stage.

**Comment by chrismplus** [comment]
@micahwalter @rdunk — closing style guide ticket.

**Comment by micahwalter** [comment]
@rdunk - Is there docs somewhere on how we can spin up this style guide on our own? Also, where is the code/markup for all the styles live?

**Comment by chrismplus** [comment]
Hi @rdunk — placing this ticket back in 'Ready'. We'll have a few projects underway that make use of this style guide so it would be good to get an understanding regarding the questions from Micah's question above.

**Comment by chrismplus** [comment]
Hi @rdunk — I think this task is self-contained (and not linked to Salesforce integration). 

Is it possible to get the codebase behind this styleguide? Can you let me know how long this task would take?

CC: @dianewang

**Comment by rdunk** [comment]
Hey @chrismplus, I'll get in touch with ZG to see if I can get a copy of the repository. If I recall correctly it was built primarily as a kind of visual tool rather than anything like a reusable framework, so the code/CSS may not be as useful as you'd like.

In terms of time, negligible amount to clone the repository, but the code could require some updates (which would take some time) if you are planning on using it as a basis for some other project.

**Comment by chrismplus** [comment]
Thanks @rdunk — the styleguide is needed for the basis of other projects. See Micah's comment from March 14 for details—I think this will help in terms of application.

**Comment by chrismplus** [comment]
Hi @rdunk — we're going to try and online tool for this first. This might be a quick way to resolve this particular parcel of work. Will loop back to you if we need further input.
