### ISSUE TITLE
Nav Bar: descriptor line: website header

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#15]
**Issue:** We were talking about how we could make this feature more fun and useful for our content. Can we use hyperlinks in this text? We would like to point visitors to various sections of the site once we start building up some content.

**Comment by rdunk** [comment]
The descriptor line has been removed from the nav bar in phase 2.

Please reopen if there is any confusion here.

**Comment by chrismplus** [comment]
We aren't currently using it but we also never discussed taking it out. Let's revisit after we've made the other changes to the nav bar.
