### ISSUE TITLE
IE11: M+ Stories logo

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#150]
The "Stories" part of the _M+ Stories_ site logo is not clickable in IE11. 

Ref: 
![image](https://user-images.githubusercontent.com/26731347/33355786-ecae61ce-d4f3-11e7-899e-bbeec05001a2.png)

**Comment by rdunk** [comment]
This is due to a really difficult bug in IE11. I've attempted a workaround in a66ba0c52eca80d5ce2f43a4b01c3920828c7f50 which seems to have fixed it, please reopen if it persists.
