### ISSUE TITLE
URGENT: unable to create new pages across the site

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#151]
A new bug has been introduced—unable to create new content stubs across the site. 

**CMS view:**
![image](https://user-images.githubusercontent.com/26731347/33412254-33d029b2-d5c5-11e7-8834-2bf24dd69f73.png)

Tested blog and episodes. Unable to publish new content in either. Tags seem unaffected.

Reference URL: https://cms.mplus.org.hk/admin/page/add/

CC: @ellenoredsson

**Comment by rdunk** [comment]
Sorry about this one. Just pushed a fix.

Looks like Processwire has a non-foolproof method of checking if a page has already been saved or not. Pages with the optional Brightcove banner field were attempting to check if the video field was empty on initial save and the CMS didn't like that.
