### ISSUE TITLE
Sitemap/Image sitemap XML

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#152]
Hi @rdunk — I just had a question about this one. I remember you saying that the image sitemap had been added to the existing [sitemap xml](https://stories.mplus.org.hk/sitemap.xml). 

I can't see how the images are being logged here, however. Could you shed some light on this? Does it need to be updated now that the rest of the site has launched, and would the existing sitemap need to be refreshed anyway?

Ref: https://support.google.com/webmasters/answer/178636?hl=en

**Comment by chrismplus** [comment]
This one is complete now @rdunk?

**Comment by rdunk** [comment]
About 90% there, just running a few more tests.

**Comment by rdunk** [comment]
Cool, should be fixed in a commit to the CMS repo and minor change in a09ebe2e06369f2d10fff84702cddf03e9b77609.
