### ISSUE TITLE
Video: load error on mobile devices

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#154]
Hi @rdunk — I've confirmed that this is still an issue, albeit seemingly only on mobile.

**Device:** iPhone 6S
**Browser:** Chrome and Safari
**OS:** 11.2
**Wifi:** WKCDA

**Steps to reproduce:** 
- Navigate to Channel: https://stories.mplus.org.hk/en/channel
- Tap on the Ho Fan video: https://stories.mplus.org.hk/en/channel/ho-fan-on-the-decisive-moment 
- Toggle language from English to TC
- Press play button and observe results

![img-7881](https://user-images.githubusercontent.com/26731347/33588931-7b60e764-d9b0-11e7-8526-712de853d3eb.png)

**Comment by rdunk** [comment]
Most likely an issue with the Brightcove CDN, are you able to consistently replicate or is this an intermittent issue?

**Comment by chrismplus** [comment]
Yes—this issue is most noticeable when I disable Wifi and use data in the office. There seems to be a correlation between not having an optimal signal and the video timing out. That would also explain why desktop remains largely unaffected.

**Comment by chrismplus** [comment]
Hi @rdunk — confirming with you that the issue here (desktop this time) appears to be on the Brightcove side? If so, I'll raise separately with Brightcove Support. 

![brightcove-support](https://user-images.githubusercontent.com/26731347/34931140-0fa4709a-fa08-11e7-843b-dc4a308c6804.jpg)

**Comment by rdunk** [comment]
Yep, can confirm it looks like this one is Brightcove specific.

**Comment by chrismplus** [comment]
@rdunk — I've logged this as an issue with the Brightcove Support team.

**Comment by chrismplus** [comment]
The issue has been raised with Brightcove support. 

Ref: 448513 Brightcove Player Issues

**Comment by chrismplus** [comment]
Closing this one for now. Error rates are being recorded now at less than 1%.
