### ISSUE TITLE
Authoring in Traditional Chinese only

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#155]
Can we find a means in the CMS to author in Chinese text only—as we can with English? I see a few cases where this would be valuable.

**Comment by rdunk** [comment]
I've just pushed some changes that should allow for this. In particular quotations were being stripped if they were Chinese only. Block text should have allowed for this already, although I added in some further validation.

I'll move this issue to "For Review", let me know if this still isn't working as expected.

**Comment by chrismplus** [comment]
Thanks, @rdunk — working as expected.
