### ISSUE TITLE
Minor: GitHub logo in footer

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#157]
Can we add the GitHub logo in the footer of the website—and link to our repository?

https://github.com/mplusmuseum/mplusmuseum-stories

I've created the base information for this—and uploaded an SVG—I can't find a way to set this logo to the footer in the CMS though.

**Comment by rdunk** [comment]
Done!

**Comment by micahwalter** [comment]
I think this should point at our main GH page - https://github.com/mplusmuseum

**Comment by chrismplus** [comment]
Good point—this has been updated.
