### ISSUE TITLE
Podium: Reprints

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#158]
**Use-case:** 

We have a Reprint text that is ready for publishing within Podium. It doesn't have an image associated with it; it's text-only. 

While the 'Leading Media' field is optional—the CMS still requires a 'Card Image'. 

Can we disable this requirement for a 'Card Image'?

**Comment by rdunk** [comment]
All the code for this is ready to push, just want to confirm something before doing so.

- You will not be able to feature/pin an article without a card image on the journal landing page.
- If you create a banner (i.e. on the homepage) and select an article without a card image, the banner will be ignored/nothing will be rendered.

If this is all OK I can push this first thing tomorrow.

**Comment by chrismplus** [comment]
Hi @rdunk — understood, this all makes sense.

**Comment by rdunk** [comment]
Done.

**Comment by chrismplus** [comment]
Confirmed this works. Moving to 'Done'.
