### ISSUE TITLE
Document upload

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#159]
Hi @rdunk — how do we handle document uploads? Such as a Word or PDF? We haven't had a need to yet funnily enough, but it's something we'll need to be able to do. Can you please advise?

**Comment by rdunk** [comment]
Ah, think I replied to this the other day and closed the tab without submitting...

Is this to make files/documents available within text content or within some kind of dedicated download page on the website?

**Comment by chrismplus** [comment]
The main use case would be within text content.

**Comment by chrismplus** [comment]
What do you mean by dedicated download page?

**Comment by rdunk** [comment]
Will implement this as we discussed with a dedicated assets section.

**Comment by rdunk** [comment]
This has now been implemented. Using it should be pretty simple:

You create new asset 'pages' under the Assets parent, assigning each a title. You then upload the relevant file to that page in the correct field. The CMS will use the page address as the URL to that file, so you can set friendly URLs for your assets. You can grab the URL from the "View" link.

<img width="325" alt="screen shot 2018-01-18 at 18 00 27" src="https://user-images.githubusercontent.com/8467307/35113544-b8c1e220-fc79-11e7-9797-5575c7be7cf8.png">

This example asset I have named "Test". Even though we have an `archive.zip` file attached, it can be downloaded from the shorter URL: `cms.mplus.org.hk/assets/test/`.

Should be really straightforward to link to assets within text this way. Just add a link as normal pointing to the asset URL.
