### ISSUE TITLE
Explore results: unexpected link behaviour

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#160]
The "Inter-Vivos" blog post card links to the "Seven Intellectuals" blog post (both are "from the collection" posts). 

Steps to replicate: 

1. Go to: https://stories.mplus.org.hk/en/explore?tag=from-the-collection
2. Click on: _From the Collection: ‘Hong Kong Inter-Vivos Film Festival’ by Ho Sin Tung_

Observe results. 

This isn't always 100% replicable— @laramplus spotted this and I could replicate the issue on my machine. 

**Results:** 
Note URL and note blog post content.
![image](https://user-images.githubusercontent.com/26731347/33818232-b392307a-de7e-11e7-93ac-b06c10a25f9c.png)

**Comment by rdunk** [comment]
Not able to replicate this one unfortunately. Any more information you could share?

Could be an issue with elements being keyed incorrectly... was it originally found when switching between tags or when accessing that URL directly?

**Comment by chrismplus** [comment]
Steps that led to result: 

First, I did a regular search with the words "From the Collection" - then from the blog post results view clicked into "Intervivos" but got redirected to "Seven Intellectuals." Back to the results view, I clicked the "From the Collection" tag from the blog post card. Two things happened: first, the tag led to "Explore" results with a bunch of collection based items (not just "From the Collection" category); then it led back to the Explore page, with no tag selected.

**Comment by rdunk** [comment]
Fixed in b8c8da394b08ef955bb7699f1dbb309673fa6214. Thanks for flagging.
