### ISSUE TITLE
HTML validator issue

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#161]
Linked to #51 

Hi @rdunk — I can't see where the HTML errors are coming from in this page. Also, when there are errors—does this affect anything with the page? I notice that I can still preview it okay...

![image](https://user-images.githubusercontent.com/26731347/33825983-64e082cc-de9e-11e7-8aa1-31199e20d0a7.png)

**Comment by rdunk** [comment]
Your HTML was indeed all valid. Looks like this was a technical issue related to the encoding of of straight quotation marks. I pushed a fix and it looks to be resolved.

And generally if you do see this message everything _should_ still work, browsers tend to manage quite well if there are minor markup errors. The validator is quite sensitive but probably best that way.
