### ISSUE TITLE
M+ Stories logo

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#162]
Hi @rdunk — can you provide us with an M+ Stories logo in both mobile and desktop lock-ups as an AI file?

**Comment by rdunk** [comment]
Both .AI files [attached here](https://github.com/mplusmuseum/mplusmuseum-stories/files/1558698/stories-logos.zip). Web ready SVGs also available in this repo:  [single line](https://github.com/mplusmuseum/mplusmuseum-stories/blob/master/src/assets/img/stories-logo-line.svg), [stacked](https://github.com/mplusmuseum/mplusmuseum-stories/blob/master/src/assets/img/stories-logo-stack.svg).
