### ISSUE TITLE
No italicisation for "+" symbol

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#163]
The "+" symbol can't be italicised in website text. 

![image](https://user-images.githubusercontent.com/26731347/34557840-83b903fa-f176-11e7-87e7-d78405d6cbd6.png)

Reference URL: https://stories.mplus.org.hk/en/blog/conserving-ink-art-for-the-weight-of-lightness-ink-art-at-m

CC: @amycmleung

**Comment by rdunk** [comment]
As far as I know many fonts don't italicise some mathematical operators. There doesn't seem to be a consensus on whether that's correct or not, though.

Not sure what we can do about this one shy of commissioning the font designer to draw a custom "+" symbol.

**Comment by chrismplus** [comment]
Will place in backburner column as non-critical.
