### ISSUE TITLE
TC 'article' card appears too long

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#164]
When compared to the English card the TC card for the Podium article appears quite long. Please see reference below:

![image](https://user-images.githubusercontent.com/26731347/34595042-a7e16dc8-f20f-11e7-83ad-b515e416ae86.png)

**Comment by rdunk** [comment]
Good catch. I've halved the excerpt length for Traditional Chinese text, it should take up a similar amount of space to English now.

Closing, please reopen if you think the length needs adjusting.
