### ISSUE TITLE
Podium home: author byline on pinned article

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#166]
Hi @rdunk — I've implemented the pinned article on the Podium landing page for the first time. Can we add an author byline to the pinned article? This will bring it inline with the banner displays for a Journal Issue, and make more sense on listings page. 

**URL:** https://stories.mplus.org.hk/en/podium

![byline](https://user-images.githubusercontent.com/26731347/34662820-59be87da-f48e-11e7-825b-581a93c3079c.jpg)

**Comment by rdunk** [comment]
Done! 7702b3ed3695bbe5c0c5452603ddb508040b5f56
