### ISSUE TITLE
Blog: video player

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#17]
**Issue:** Video player content does not always load into the page. Strangely, this only affects certain players; some still work. Refer to screenshot, leading video and video in the 'Sucker' blog post have not loaded correctly. However, the video for the first blog post is fine. 

**Expected behaviour:** Video players should load every time.
![video-player-load-issues](https://user-images.githubusercontent.com/26731347/30145715-e3827b72-93c5-11e7-959d-232849225214.jpg)

**Comment by chrismplus** [comment]
Hi @rdunk -- this seems to be a related bug of the Brightcove issue we spoke about during our call regarding the site not always bringing in the player.

**Comment by rdunk** [comment]
@chrismplus To confirm, occasionally the video/player does not load **at all**? I haven't come across this, only that the incorrect player is used (default Brightcove player instead of M+ specific player). Will investigate.

**Comment by chrismplus** [comment]
@rdunk yes, the player fails to load. The attached screenshot shows an instance where two players have failed to load, whilst the M+ building video does load in. All videos are coming from the same folder in Brightcove.

**Comment by chrismplus** [comment]
Closing this one for now as we cover this in [Issue #35](https://github.com/mplusmuseum/mplusmuseum-stories/issues/35). Will re-open if necessary.
