### ISSUE TITLE
Accessibility: non-text content 1.1.1

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#170]
_Please cross-reference against Web Accessibility Evaluation Report, pp. 4-5._ 

**Issue 001: The language of the alternative text for images is incorrect**

- [x] **Example 1:** ALT text of some images improperly assigned in English
- [x] **Example 2:** no ALT text assigned to interactive images

**Comment by rdunk** [comment]
I've pushed a update 4496831d93cd705a1fb36ab2072b89bd2e833247 which should resolve a lot of these accessibility issues. Will go through and tick specifics off next week.

**Comment by chrismplus** [comment]
Passed re-test. Moving to 'Done'.
