### ISSUE TITLE
Accessibility: information and relationships 1.3.1

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#171]
_Please cross-reference against Web Accessibility Evaluation Report, p. 6._

**Issue 001: Inappropriate markup for headings**

- [x] **Example 1:** H4 heading markups should be used in order to distinguish them from the H3 section heading.
- [x] **Example 2:** Two heading levels are used on the title of the entries. H3 for blog post and H4 for video.

**Comment by rdunk** [comment]
Fixed so all grid items now use h4 for titling.

**Comment by chrismplus** [comment]
Passed re-test. Moving to 'Done'.
