### ISSUE TITLE
Accessibility: pause, stop, hide 2.2.2

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#173]
_Please cross-reference against Web Accessibility Evaluation Report, p. 8._

**Issue 001: Infinitely looping animated content**

Re: animated header ["NOW VIEW THIS"]
- [x] Should read as a header on screen readers, shouldn't repeat. 
- [ ] Idea: can we implement a hover state that says something along the lines of 'tap to pause'. Thoughts? Might be more graceful than stopping the animation after 5 seconds.

**Comment by rdunk** [comment]
First item fixed in c7a2d14134d31e0969725ad826a627e75359d775.

**Comment by chrismplus** [comment]
H @rdunk — please see comment from HKBU below: 

**Ideas:** 
- Can we implement a solution that stops autoplaying content (video) on hover/or when the item is tabbed on? 
- For the "Now Read This"— can we slow down the scroll slightly? 

![image](https://user-images.githubusercontent.com/26731347/35610232-72793940-069b-11e8-9609-8573f6da01df.png)

**Comment by rdunk** [comment]
For marquee elements: Click to pause has been added in bf06c2b66c750538486991e334ad15b635dc6103 and the animation has been slowed by 50% in 5a507a040216598c71231f24a02f4107924ad848.

The article linked seems to be referring to autoplaying videos with audio, which I agree is definitely an accessibility concern for all types of user. However audio is explicitly disabled in the case of the M+ Stories website. My feeling is a hover pause function would perhaps be more confusing for users, if this is requirement has to be met, I would suggest that only static images are used, but I'm not sure how [content like this](https://stories.mplus.org.hk/en/blog/five-things-to-look-for-when-watching-san-yuan-li-by-u-theque) would be possible, as you'd have to have a policy of removing all animated GIFs, too.

**Comment by chrismplus** [comment]
> For marquee elements: Click to pause has been added in bf06c2b and the animation has been slowed by 50% in 5a507a0. 
— @rdunk; the above hasn't been pushed to Production yet?

**Comment by rdunk** [comment]
Good point, has now!

**Comment by chrismplus** [comment]
@chrismplus is following up with the HKBU.

**Comment by chrismplus** [comment]
@rdunk — I've discussed with HKBU, can we include keyboard support for the marquee "NOW VIEW THIS" element? This would look like:

- When keyboard focus is on the marquee element it pauses.
- When keyboard focus is on the marquee element, it stops when the user presses "Return". 

Regarding auto-playing videos: our current solution is fine taking into account the fact there's no sound, and it's not the actual video. The recommendation has been to keep videos slow. I'll pass this feedback onto the team. Let me know how you go with the keyboard support for the marquee element.

**Comment by rdunk** [comment]
Does this mean making the marquee element a button? At the moment you can't tab over it as it's just a regular non-interactive element.

**Comment by rdunk** [comment]
Implemented in 083e0f831e7ef67f7119607922f4b358a5ce466c.
