### ISSUE TITLE
Accessibility: labels or instructions 3.3.2

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#175]
_Please cross-reference against Web Accessibility Evaluation Report, p. 11._

**Issue 001: Missing or improper label for form fields.**

- [x] **Example 1:** labels of input boxes improperly assigned. 
- [x] **Example 2:** text not descriptive enough or in the wrong language.

**Comment by rdunk** [comment]
Addressed input fields in 96579036b14319d899d27b9a96e1d6081b5918b6.

**Comment by chrismplus** [comment]
Hi @rdunk — in the "Translate accessibility.php to Traditional Chinese" file, I wanted to seek clarification on the following three elements, can you send me references for what these are?

1. Return to Contents (Alt text for contents icon)
2. Series Icon (Alt text for series icon) — assuming this is Channel related?
3. Placeholder image (Alt text for placeholder image)

**Comment by chrismplus** [comment]
Hi @rdunk — chasing up for an update on the comment above. Can you send references, or provide descriptions of what the three items are in the comment listed above? This will help @amycmleung translate. Thanks.

**Comment by rdunk** [comment]
Missed this one before.

1. Return to Contents – used as the alt text for the up arrow that returns the user to the contents listing on any documentation pages (e.g. terms & conditions). You're not currently using the contents feature for your documentation pages, so this one actually won't show up anywhere at present.
2. Series Icon – correct, used as the alt text for the series icon in Channel.
3. Placeholder image – This is the alt text for any fallback images in the suggested items panel, for example if somehow a page is saved without a key image. Very rare that these would actually be used. Perhaps we should override to make screenreaders avoid these anyway.

**Comment by chrismplus** [comment]
Passed re-test. Moving to 'Done'.
