### ISSUE TITLE
Accessibility: on input 3.2.2

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#176]
_Please cross-reference against Web Accessibility Evaluation Report, p. 12._

**Issue 001: Pop-up window opened without notification.**

Chris following-up with vendor for further details.

**Comment by chrismplus** [comment]
@rdunk 

Further information from HKBU: 

> There are some links which will redirect user to a page in a new browser window. It is recommended that a phrase "(opens in new window)" is added to the link to inform user about this in advance. You may refer to the following link for details,
>  
> G201: Giving users advanced warning when opening a new window
> https://www.w3.org/TR/WCAG20-TECHS/G201.html

I don't think there are too many examples of this. One would be the NeonSigns exhibition link-out: 

![image](https://user-images.githubusercontent.com/26731347/34903186-393d426c-f867-11e7-83ef-3a2213d752e4.png)

**Comment by rdunk** [comment]
Fixed in 7948748a88f875f9f6f5cc60b2a7a1ad80e1e543. Screen readers should now consistently read out the item type and whether it's an external link, so in this case: ”Interactive External Link NEONSIGNS.HK"

**Comment by chrismplus** [comment]
Hi @rdunk — has this also been applied to links in the footer? 

Comment from HKBU: 

![image](https://user-images.githubusercontent.com/26731347/35609979-9c21cd26-069a-11e8-8705-7186c297263c.png)

**Comment by rdunk** [comment]
The "External Link" accessibility translation is now appended to all social platform links (a9186269d7e198074236db5d4b1d956ec3fafec5) and to the West Kowloon link (c48237009eb848d2da154719558224c779f5ca2e) in the footer. Hope that's sufficient!

**Comment by chrismplus** [comment]
Thanks @rdunk — has this one been pushed to Production?
