### ISSUE TITLE
Blog: categories

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#178]
@rdunk—

Can we allow a blog post to be placed into multiple categories? 

CC: @ellenoredsson

**Comment by rdunk** [comment]
Implemented in 5e658153b719e5f83f887ebc28fa5d7b07482f25. The 'category' field has been replaced with a new 'categories', and the data from the previous field has been copied over so each post still has one category assigned.

**Comment by chrismplus** [comment]
Thanks, @rdunk. @ellenoredsson tested—moving to complete.
