### ISSUE TITLE
CMS: image upload for all media

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#18]
CMS LEVEL BUG. CAN'T BE ADDRESSED RIGHT AWAY. LOOK TO PHASE 2.

Issue: If an image is replaced in the CMS with a new asset, the Traditional Chinese alternative text and description are wiped out.

Expected behaviour: Alt text should remain, as it does with English text.

**Comment by rdunk** [comment]
See processwire/processwire-issues#489.

**Comment by rdunk** [comment]
I've bumped ProcessWire to the latest version which includes a fix for this issue.
