### ISSUE TITLE
Explore: tag search not working properly

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#180]
@rdunk: 

Can you look at addressing this one straight away? The tag-explore interface is behaving unexpectedly. It's missing text in the search bar, multiple tags can't be selected concurrently, nor can the first tag that's been selected be removed. 

URL: https://stories.mplus.org.hk/en/explore

**Comment by rdunk** [comment]
Fixed in 14091726c3e38faf94d67401628e5cd851620239. Looks like a plugin we're using dropped support for a function used for looping through the tags, added it back in.
