### ISSUE TITLE
View this now > Showing the article that I'm on

### ISSUE THREAD

**Issue by dianewang** [mplusmuseum/mplusmuseum-stories#184]
Hey @chrismplus can you try to see if this happens to you as well. cc @ellenoredsson 

I've managed to replicate it a few times and also in cognito in Chrome.

Here's the sequence:
1. Navigate to a blogpost
2. Click on a "View this Now" blogpost
3. Scroll down to the "View this Now" section"

The blogpost that you're on is still visible, and in addition - the "View this Now" doesn't always refresh itself, meaning it's the same as the three before.

I've included screenshots including the URL of the page that I'm on.

![screen shot 2018-02-02 at 4 38 43 pm](https://user-images.githubusercontent.com/4805479/35724288-223374fc-0838-11e8-9fae-b5fd64230f08.png)
![screen shot 2018-02-02 at 4 39 21 pm](https://user-images.githubusercontent.com/4805479/35724289-225b2c04-0838-11e8-94b3-8d225fa8c6bb.png)

**Comment by chrismplus** [comment]
@dianewang can you walk me through this one? 

Is the issue that the 'related' material remains the same?

**Comment by chrismplus** [comment]
@rdunk — 

See issue above. The "Now View This" content doesn't update when you click through to a new blog post via the "Now View This" portal. However, if the page is refreshed, the "Now View This" content _does_ update. 

Confirming that the logic behind "Now View This" is drawn on tag similarity?

**Comment by rdunk** [comment]
Also seeing this. Seems the lazyloading of this component means it's functionality wasn't being triggered when navigating to the same view/template. Fixed in 18e04c087798b34c2725da1fce343f17ee0a33e5.

**Comment by chrismplus** [comment]
Hi @rdunk — as discussed in the meeting can you check the logic behind this one? I think if we can preference 'category' above tag that would be good. Do let me know if this turns out to be complicated, however.

**Comment by rdunk** [comment]
Logic is as follows:

1. The front-end makes a request to the server, the payload of that request is the id of the piece of content requesting related items.
2. The server checks to see if any related content has been manually set. If there are enough to meet the minimum number of items required (default is 3), it returns them.
3. If more are needed, it runs a database query to find content with common tags, categories (blog only) or series (channel only).

I believe at the moment tags may take precedence, as they are specified first in the query. I've switched those round and will test with the production data tomorrow.

**Comment by chrismplus** [comment]
Thanks @rdunk

**Comment by rdunk** [comment]
Working and pushed to production. Categories and series now take precedence over tags.
