### ISSUE TITLE
Fix staging deployment

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-stories#186]
We are working on fixing the setup on staging which might be conflicting with other apps on that same server.

**Comment by micahwalter** [comment]
@rdunk @chrismplus  - I need to take a break from this for today. But here's what I've found:

1. We need documentation on how to get this to build, including a bit about the font files, .env files, etc. 

2. Once I re-copied the font files, I was able to get things running on my laptop when pointed at the staging-cms ( the point of this exercise )

3. It will now build and run on the staging/admin server. However, it only seems to work when pointed at the live CMS vs. the Staging CMS. Not sure why, and am unable to replicate the errors I get locally.

4. Once we get this to work, we should come to an agreement on package managers ( we are using Yarn vs. npm ) and we should rename the PM2 process to be the same as the repo name... mplusmuseum-stories

```
0|stories  | n { resolved: false, status: false, data: { errors: [] } }
0|stories  | error during render : /en/
0|stories  | n { resolved: false, status: false, data: { errors: [] } }
0|stories  | error during render : /en/
0|stories  | n { resolved: false, status: false, data: { errors: [] } }
0|stories  | error during render : /en/
0|stories  | n { resolved: false, status: false, data: { errors: [] } }
0|stories  | error during render : /en/
0|stories  | n { resolved: false, status: false, data: { errors: [] } }
0|stories  | error during render : /en/
0|stories  | n { resolved: false, status: false, data: { errors: [] } }
0|stories  | error during render : /en/
0|stories  | n { resolved: false, status: false, data: { errors: [] } }
0|stories  | error during render : /en/
0|stories  | n { resolved: false, status: false, data: { errors: [] } }
```

**Comment by chrismplus** [comment]
@rdunk — can you see where you can chip in on the above?

Re: build documentation— is there any cross-over here with the existing set of documentation that's being created?

**Comment by rdunk** [comment]
I've updated the README and .env.example file now. It should be clear that there are two environment variables that are required for the app to build. One for the API endpoint, one for the url/path to the font files. Let me know if you're still having trouble, I can look into adding some kind of warning for these if they're omitted.

**Comment by chrismplus** [comment]
@micahwalter @rdunk — okay to move this one over to 'Done'?

**Comment by chrismplus** [comment]
@micahwalter

**Comment by rdunk** [comment]
I think we can assume this one is resolved, the README and documentation make all the required environment variables clear and the font files are now hosted externally.

Regarding point 4, I prefer npm over yarn and I've removed all references to yarn from the repo (the installation instructions also state npm)—however if there needs to be a consistent approach across all M+ repos and the use of yarn is required, that can be changed easily via a new commit / pull request, it shouldn't require any input from me.
