### ISSUE TITLE
Add MCE campaign tracking tag

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#187]
Details in email sent on 6/2.

**Comment by rdunk** [comment]
Hey @chrismplus, would you be able to forward me the email of our previous correspondence? I don't have access to that account anymore.

Regardless, my GTM experience is quite minimal and I've never actually done an integration of GTM with Vue before, although I know there are packages out there, [vue-gtm](https://github.com/mib200/vue-gtm) seems the most popular.

I am currently working on another Vue project with GTM as a definite a requirement, I'm looking to get it working with the app in the next two weeks or so. We could always add a custom event through GA for now and I could work on a GTM integration for Stories once I've had some more experience with it (just conscious of using up monthly time allowance working it all out at present, but also happy to do it sooner if necessary).

Can you give me some more details about what exactly you're trying to track?

**Comment by chrismplus** [comment]
Hi @rdunk, thank you. Details will be in email.

**Comment by chrismplus** [comment]
We have some more details. The interim approach that's been suggested is that we implement the Google code only on pages that are featured in the online banners. I'll email you the details to give you a sense of how long this might take. I'd like to be judicious with maintenance hours this month until we have the navigation updated.

**Comment by rdunk** [comment]
Picking up some outstanding tickets, any update on this one @chrismplus?

Last correspondence I can find was on the 25th Jan, not sure if there was anything more to come after 1 Feb. Let me know if so!

**Comment by chrismplus** [comment]
Thanks, @rdun. I'll close this issue for the moment. We're hoping GTM integration will speak to these issues moving forward.
