### ISSUE TITLE
Unable to embed 360 still through iFrame

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#188]
CMS not allowing iFrame code to display on front end.

Link in CMS: https://cms.mplus.org.hk/admin/page/edit/?id=2515&s=1&c=0

**Comment by rdunk** [comment]
Seems the markup was invalid, had it been copied from a script by any chance?

**Comment by chrismplus** [comment]
Yes, it was copied from a script (from the platform).

**Comment by rdunk** [comment]
Looks like it was an extract of Javascript rather than HTML.
