### ISSUE TITLE
'Up Next' video content

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#191]
This seems to have dropped off the site when the 360 video player was made.

**Comment by rdunk** [comment]
This still seems to work OK for me. e.g. on [this page](http://localhost:8080/en/channel/tiffany-chung-revealing-history).

This was only ever implemented for videos in the Channel section as far as I recall.

**Comment by chrismplus** [comment]
This is strange—this feature hasn't been functioning for a few months since we did some work with Brightcove for the 360 player. 

I can confirm it's working once more on Channel though. However, if we look at the end of the Ming Wong video, it's linking to non-video material: 

![image](https://user-images.githubusercontent.com/26731347/43934657-f4a07f28-9c82-11e8-9b5d-02dec9db2e55.png)

The middle link above is a blog post in this instance.

**Comment by rdunk** [comment]
Ah, good spot. Seems it was picking up the manually set related content, should only return other channel episodes now.

**Comment by chrismplus** [comment]
Thanks, @rdunk — checked it. Looks like it's working as expected.
