### ISSUE TITLE
Clearing 'Search' terms

### ISSUE THREAD

**Issue by dianewang** [mplusmuseum/mplusmuseum-stories#192]
After I've searched something and navigated away from the search results page, my Search terms continue to persist. The expectation though, is that Search should 'reset' and clear after I've navigated away as most likely I'm going to search something new.

Steps:
1. Click the search icon and search something, e.g. 'samson'
2. Click on a post from the Search results page
3. Click the search icon again, and you'll see that the term 'samson' persists

**Comment by chrismplus** [comment]
Hi @dianewang — this has been fixed. Let me know whether you encounter any further issues.
