### ISSUE TITLE
Analytics > Homepage URL /en/ vs /en

### ISSUE THREAD

**Issue by dianewang** [mplusmuseum/mplusmuseum-stories#199]
URLs sometimes have an extra forward slash versus not within our site behaviour. 

Example:
If I type stories.mplus.org.hk into my browser, it resolves to https://stories.mplus.org.hk/en/
However, if I click the M+ Stories logo on the site, I end up at https://stories.mplus.org.hk/en

Can we make these consistent to alleviate some of the discrepancies in analytics?

**Comment by rdunk** [comment]
In commit 9857cbba8bbd85af7dfa18b1bff5e9cd837d5d08 on the develop branch I've enforced trailing slashes for all URLs, and added redirects for those that don't have one. So `https://stories.mplus.org.hk/en` will now always redirect to `https://stories.mplus.org.hk/en/`, etc.

Can't push this one to staging yet/master branch (still seeing problems with AWS instances), but will as soon as those are resolved and move to the For Review queue.

**Comment by chrismplus** [comment]
Thanks Rupert
