### ISSUE TITLE
Website should fail more gracefully

### ISSUE THREAD

**Issue by micahwalter** [mplusmuseum/mplusmuseum-stories#2]
Following the instructions and running `$ yarn` on my system resulted in lots of errors. I am assuming there are some other dependancies I need installed. These should be documented, and the code should be able to deal without them if necessary.

**Comment by rdunk** [comment]
Are you seeing errors when running the installation command `$ yarn` or when running the build / dev scripts? The latter will be related to missing font files, will try to resolve this soon.

**Comment by micahwalter** [comment]
Yes, on closer inspection it's having to do with the missing fonts...

**Comment by micahwalter** [comment]
Closing this as food for thought...
