### ISSUE TITLE
Feature regular 'Pages' on homepage

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#205]
Feature non-section based pages on the homepage, i.e. https://stories.mplus.org.hk/en/ask

**Comment by rdunk** [comment]
Technically this isn't _too_ complicated to add in, but a few questions:

1. Is support for pages to be displayed as banners required? The required fields for this don't exist at present.
2. Is support for pages to be displayed as cards (i.e. in content lists) required?
3. Each card has a slightly different design dependent on the content it represents, what should page cards look like? Basic page and Documentation page templates don't currently have card image fields, would the cards need to display an image?
4. Pages are not taggable, so pages would not appear in content lists auto-generated from a selected tag, is this OK?
5. Pages would not appear in recent content lists, is this OK?

**Comment by chrismplus** [comment]
Hi @rdunk —

I think we can keep this relatively simple from a display perspective. The use-case for displaying basic pages on the homepage is primarily for a calls-to-action for time-sensitive comms (i.e. vote next on an object to look at from the collections, ask a curator etc.).  

So, we'd only need a banner element. 

To your points: 
- Let's forgo the card element; we'll only use banner elements;
- It's okay that pages are not taggable in this context; 
- It's also fine that pages won't appear in recent content lists.

**Comment by rdunk** [comment]
I've reviewed all the necessary code changes for this... not _quite_ as straightforward as I'd originally assumed but still possible.

We'll need to create a special field to make these banner-only, as all of the banner logic at the moment relies on being able to fallback to a required card image field, and that doesn't/won't exist on these types of pages.

So next question, should banners for these pages support images *and* video (upload and via brightcove id)?

**Comment by chrismplus** [comment]
Hi @rdunk — yes, let's include image and video support (via Brightcove ID).

**Comment by rdunk** [comment]
Will push this to production Monday AM.

**Comment by chrismplus** [comment]
Great—thanks @rdunk

**Comment by rdunk** [comment]
Pushed. Just to note that the banner fields aren't required in order to publish a page, but you'll need to add a banner image/video etc to pages before featuring them on the homepage.

**Comment by chrismplus** [comment]
Noted, thanks @rdunk. Tested and working as expected.
