### ISSUE TITLE
LinkedIn unable to read Stories images when sharing content

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#208]
LinkedIn is unable to read images when posts are shared on their platform. 

**Post inspector link:** https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fstories.mplus.org.hk%2Fen%2Fpodium%2Fissue-2%2Fstrange-days

![image](https://user-images.githubusercontent.com/26731347/43889392-9ffd840c-9bf6-11e8-8284-1246b8feea72.png)

![image](https://user-images.githubusercontent.com/26731347/43889427-bb078b62-9bf6-11e8-91cc-b4579abf87a2.png)

**Comment by rdunk** [comment]
Looks as if the the `name` attribute was being used instead of the `property` attribute for opengraph tags. Assuming this hadn't been noticed before as other platforms may use the `name` attribute as a fallback.

**Comment by rdunk** [comment]
Pushed this to production, looking good...

<img width="561" alt="screen shot 2018-08-09 at 17 16 54" src="https://user-images.githubusercontent.com/8467307/43911740-1ee90272-9bf8-11e8-8ead-1d9cb3052e03.png">

**Comment by chrismplus** [comment]
Thanks, @rdunk — works well
