### ISSUE TITLE
Website not loading 'hero', or, leading image as expected through 'related' module

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#209]
This only seems to happen when linking to a piece of content via the 'now view this' module. Steps to reproduce: 

1. Clear cache
2. Go to blog: https://stories.mplus.org.hk/en/blog
3. Scroll to the current 3rd piece in the blogroll: https://stories.mplus.org.hk/en/blog/how-mplus-is-a-lab-for-learning
4. Scroll to the bottom of the blog and click on a related piece of content, eg: https://stories.mplus.org.hk/en/blog/curating-conserving-canton-express-chickens-in-the-gallery
5. Observe results: 
![image](https://user-images.githubusercontent.com/26731347/44032290-455682f6-9f39-11e8-8fac-645f6a85524b.png)

Notes: 

- You might need to loop through the above cycle a few times—i.e. keep on loading related content. I've tested this across devices. It seems most prevalent on Desktop—but it is a consistent issue. 
- It seems to only affect blog post leading images. Podium/Channel seem unaffected. 
- The issue cannot seem to be recreated if a 'related' blog is opened in a new tab or window. It only occurs if linking through within the same window. 

This is the only error I could find through the console (Safari—Chrome and Firefox didn't seem to log any errors): 
![image](https://user-images.githubusercontent.com/26731347/44078613-8a615722-9fd9-11e8-956e-0a1ff49f722b.png)
![image](https://user-images.githubusercontent.com/26731347/44078680-b5a37294-9fd9-11e8-914b-09ec63ed9911.png)

**Comment by chrismplus** [comment]
@rdunk, @zakkyes — I've moved this one to the top of the queue. I hope it's an easy fix.

**Comment by rdunk** [comment]
I think I know why this might be happening, pushed a fix in d442786. Can't replicate on my end anymore but please flag if you can.

**Comment by chrismplus** [comment]
The leading image no longer seems to be affected. But the images within a blog post still don't always load. Again, this seems to be in line with what was happening with the leading image, in that they don't load only when linked to through 'related content'. When I load the URL directly, the images load as expected. 

I've particularly noticed it with the following posts when accessed through the 'related' module: 

- https://stories.mplus.org.hk/en/blog/curating-conserving-canton-express-preserving-the-history-of-tomorrow
- https://stories.mplus.org.hk/en/blog/m-rover-experimenting-learning-with-participatory-art

-

**Comment by chrismplus** [comment]
Here's what I'm seeing on my end when loading [this page](https://stories.mplus.org.hk/en/blog/m-rover-experimenting-learning-with-participatory-art) through the related content module: 

![image](https://user-images.githubusercontent.com/26731347/44082240-37f3164c-9fe3-11e8-8a44-bed4918fffd3.png)

**Comment by chrismplus** [comment]
Thank you

**Comment by chrismplus** [comment]
Hi @rdunk — I'd like to loop back to this issue while we await the dependency work to take place on the AWS side of things. Would you be able to have a look at this one?

**Comment by rdunk** [comment]
Hey @chrismplus, sorry for the delay on this, will have a fix ready before the end of the week.

**Comment by rdunk** [comment]
Reverted the previous commit and pushed a fix for this to production.

**Comment by chrismplus** [comment]
Thanks, @rdunk — now working as expected. Closing issue.
