### ISSUE TITLE
Two-step authentication

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#21]
Following meeting today with @micahwalter -- needs investigation.

**Comment by rdunk** [comment]
I've done some more research on this today. Can you confirm if two-factor authentication is preferred over two-step verification? My understanding was the latter would be preferable but I wanted to check.

It looks that either method is going to require a custom implementation as the currently available open-source options for ProcessWire are not looking like viable options at this point.

**Comment by chrismplus** [comment]
Can you outline what the two methods would look like in ProcessWire?

**Comment by rdunk** [comment]
Basically, two-step would be something like a required username/password and a one time password being sent to the user's email address.

Two-factor would require using something like an app (e.g. [authy](https://authy.com/)) that users would need to install on their mobile devices.

Basically, the latter is considered more secure as it technically requires theft of both knowledge i.e. username/password as well as theft of a physical device. The former effectively only requires knowledge (although this is debatable!).

Both would require us to alter how the CMS handles logins, as it doesn't support anything like this out of the box. Two-step would be something like:

- login with username / password
- email sent to user email address with OTP that expires after a set period
- user is shown a second 'login' page with a field to enter the OTP
- once OTP is entered, user is shown the normal admin interface

Two-factor I would need to look into more to give you an exact breakdown of how it would work, but I imagine it would be vaguely similar but would probably require a OTP acquired from a third-party app on a mobile device.

**Comment by chrismplus** [comment]
Thanks for the overview @rdunk. I've fed this back to ICT--awaiting input.

**Comment by chrismplus** [comment]
@rdunk —

*from ICT:* 
Please check if you are able to enforce the validity period (limit it within 1 mins) of 2-step, if so, it is much better than just username/password authentication.

**Comment by chrismplus** [comment]
Hi @rdunk — are you able to shed some light on the above comment raised by ICT?

**Comment by chrismplus** [comment]
@rdunk — I'd like to feedback on this sooner rather than later.

**Comment by rdunk** [comment]
As there's no existing functionality for any of this we would be building a completely custom authentication process, so technically that is possible. Is ICT's preference two-step over two-factor?

**Comment by chrismplus** [comment]
M+'s is two-step (as described by you above). But to do this we need to satisfy ICT's concerns—hence their suggestion regarding the validity period.
