### ISSUE TITLE
Multilingual sitemap

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#210]
Ensure Chinese-language front-end content, as well as metadata (i.e. alt text), is open to being indexed by search engines.

**Comment by chrismplus** [comment]
Hi @rdunk — is this something that we can look at this month?

**Comment by rdunk** [comment]
I've read up a bit more on this. There seem to be some constraints with multilingual sitemaps that make things like image captions impossible to have in more than one language.

I think it might make sense to split the sitemap in two, i.e. have a separate sitemap for each language. I need to do a little bit more research to make sure this isn't going to cause any problems, but I've had a look into the implementation side and made all the changes necessary to do this already, so should be able to get this live this week.

**Comment by chrismplus** [comment]
Great 👍

**Comment by rdunk** [comment]
This one has been deployed, so there are two new links to be aware of (and add to Google Webmaster Tools etc).

https://stories.mplus.org.hk/en/sitemap.xml
https://stories.mplus.org.hk/tc/sitemap.xml

The previous URL will redirect to the English version by default.

**Comment by chrismplus** [comment]
This has been completed by MCE—no need for a new verification. 

Closing this issue.
