### ISSUE TITLE
Add reading duration to content cards

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#211]
Adding this to the task backlog: can we investigate adding 'reading time' to content cards (Podium/Blog pieces)—similar to what we do with video duration?

**Comment by rdunk** [comment]
Sure, totally possible. Had you imagined this would be automatically calculated somehow or input manually?

**Comment by chrismplus** [comment]
Automatically calculated—same as the Channel cards

**Comment by rdunk** [comment]
Might need to discuss some criteria for how this is calculated before we can implement, [useful reference?](https://help.medium.com/hc/en-us/articles/214991667-Read-time)

**Comment by chrismplus** [comment]
Hi @rdunk — the English reading speed of 265 WPM feels good. I think we should adjust the formula slightly for traditional Chinese. Let's go with 450 characters/min.

**Comment by rdunk** [comment]
Have this almost ready to go. Is the expected reading time for Traditional Chinese quite a bit longer than for English? Calculation function might need tweaking. From a random selection, calculated times in minutes:

|English|Traditional Chinese|
|---|---|
|7|17|
|5|11|
|4|6|
|4|9|
|3|8|
|4|9|
|6|13|
|5|11|

**Comment by chrismplus** [comment]
Hmmm... Chinese reading time usually comes out as being calculated a bit quicker than English.

**Comment by rdunk** [comment]
Looks like I made a really silly mistake in counting CJK characters, used a non-multibyte function which can only really be used for Latin characters. Tweaked it and the results are now what we were expecting. Will try and get this one deployed tomorrow AM.

**Comment by chrismplus** [comment]
Good to hear, thanks Rupert. What part of the tile would this information be displayed on?

![image](https://user-images.githubusercontent.com/26731347/49202650-3b6ca580-f3e0-11e8-8233-6da08b05e8f2.png)

**Comment by rdunk** [comment]
I've deployed this for Podium Article cards and Blog Post cards. The logic for the placement follows from Video/Episode cards, so it always sits below the title. I'll move to review for now, let me know your thoughts or if anything needs changing.

**Comment by chrismplus** [comment]
Thanks, @rdunk — works well.
