### ISSUE TITLE
Indented text colour

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#219]
When text is 'quoted' in the CMS it's rendered in a light grey colour. 

![image](https://user-images.githubusercontent.com/26731347/46646515-3435d200-cbbd-11e8-8606-c968e9b293c9.png)

This is especially difficult to read on the Podium pages which place text on a grey background. Can we make this text just render in black? 

![image](https://user-images.githubusercontent.com/26731347/46646463-e4570b00-cbbc-11e8-9e39-e1d98a138ada.png)
Blog example

@rdunk — hopefully this is a quick one to solve?

**Comment by rdunk** [comment]
Updated in fbf09008448f43b5170758af88f0b89f128a858b.
