### ISSUE TITLE
Apostrophe issue with sharing content

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#22]
Formatting issue occurs with text when '' apostrophes are used in the title. However, curly apostrophes are fine: ‘’.

**Comment by rdunk** [comment]
Attempted fix in 01fe306811fe4a28adeba35b40fbfafd57a3b006.

Needs more testing.

**Comment by chrismplus** [comment]
Tagging in @ellenoredsson for help with testing.

**Comment by rdunk** [comment]
This was related to the other sharing issue, introduced a hopefully more reliable method in fb8d9d10548089f2d009e437d2c6bdc54e54bf01. Still recommend testing!

**Comment by chrismplus** [comment]
Thanks, @rdunk — we'll keep an eye out on how this behaves.

**Comment by rdunk** [comment]
Think we can close this one now, tested with the dedicated sharing text field and looks like straight quotes are no longer an issue. I would urge editors to use curly quotes wherever possible though as these are favourable from a typographic standpoint.

**Comment by chrismplus** [comment]
Hi @rdunk — we've had an instance today of this apostrophe issue raising its head. Please see image below from Slack share: 

![image](https://user-images.githubusercontent.com/26731347/33698587-810a46e4-db48-11e7-960a-451a9af179f9.png)

**Comment by chrismplus** [comment]
Thanks @rdunk — we agree that curly quotes are better — but the default keyboard entry for apostrophes in the CMS is straight quotes. Can we make apostrophes curly by default? This would make it a lot easier to manage. We have to enter apostrophes outside of the CMS at the moment.
