### ISSUE TITLE
Interactives: curatorial statement

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#221]
Hi @rdunk —
this task has some urgency to it so would you be able to prioritise this one as we'll need to push an update to the site within the month? 

We'd like the ability to include a curatorial statement alongside an interactive project. The curatorial statement could simply link to an info page (I think the template we currently use for the 'About' page), kind of like what we do with the transcripts for Channel videos. 

Could we integrate it with the banner element of an 'Interactive'? I think we can keep an Interactive's tile styling as is. 

Can you let me know what you think and how long a task like this might take?

CC: @dianewang

**Comment by chrismplus** [comment]
Hi @rdunk — I just wanted to check in with this one—can you let me know what you think? 

CC: @dianewang

**Comment by rdunk** [comment]
This is ready to go, the links/buttons will show wherever the Interactive appears as a banner and will replace the whole banner click link. The curatorial statement link is optional, if it is not provided the banner will look and function exactly as they do now.

There will also be two new translations for "Launch Project" and "Curatorial Statement" which will need to be set, also do let me know if those defaults should change. 

Will push the update if you think the screenshot below looks OK.

<img width="1680" alt="screen shot 2018-10-22 at 11 33 21" src="https://user-images.githubusercontent.com/8467307/47290233-66502680-d5f6-11e8-9038-0cb8f72dc6b2.png">

**Comment by dianewang** [comment]
@rdunk this looks great! Just some minor feedback:

Could we add the "link out" icon from the subtitle Online Exhibition also onto the "Launch Project" button?

I am thinking that "View the Project" or "See the Work" might be better for the button language, but will discuss this internally. 

Otherwise, looks great!

**Comment by chrismplus** [comment]
@rdunk — 

here are the translations: 

- Launch Project: 前往項目
- Curatorial Statement: 策展人的話

**Comment by chrismplus** [comment]
Hi @rdunk — I'll be on-hand to test this today if it's ready to push to production?

**Comment by rdunk** [comment]
On it now. Should be live in the next 15 minutes.

**Comment by chrismplus** [comment]
Hi @rdunk — thanks for that. I've tested and it's working as expected. 

To loop back on @dianewang's comment, can we include the 'link out' icon on the "Launch Project" button?

**Comment by rdunk** [comment]
Should be there, pushed that change a few seconds before your comment! Might need to refresh?

**Comment by chrismplus** [comment]
Hmmm... I'm still seeing this across browsers:

![image](https://user-images.githubusercontent.com/26731347/47421781-e40d6100-d7b3-11e8-9035-6b99252a68af.png)
![image](https://user-images.githubusercontent.com/26731347/47421792-e7a0e800-d7b3-11e8-9386-59b1df2e1bd6.png)

**Comment by rdunk** [comment]
Hm, could be because of the microcache. Can you check again in a few minutes? Can't think why else it wouldn't be showing.

**Comment by chrismplus** [comment]
How long does microcache generally take to update? No change yet. I'll try again before leaving tonight

**Comment by chrismplus** [comment]
@rdunk — yes, it's still not updating as of this morning either.

**Comment by rdunk** [comment]
Apologies, oversight on my part. Was only being applied to banners on the homepage, should be fixed now.

**Comment by chrismplus** [comment]
Thanks, @rdunk — working as expected now. Closing ticket.
