### ISSUE TITLE
Staging CMS preview

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#222]
Hi @rdunk — the 'View' button in the staging site CMS is currently pointed to the front-end of the production site, instead of the front-end of the staging site. 

Let me know when you get to this one and I'll send you additional details. 

![image](https://user-images.githubusercontent.com/26731347/47410221-ab5f8e80-d797-11e8-8d09-ebf32b5a35b7.png)

**Comment by rdunk** [comment]
Hey @chris, is it still the case that the staging CMS is linked to the production database or have these been separated now?

**Comment by chrismplus** [comment]
These are currently being looked at. I was testing this morning and noticed a bug. Hopefully, it will be resolved soon. Shall we wait for this fix to be in place before altering this button?

**Comment by chrismplus** [comment]
@rdunk — the two instances (staging/production) have been separated now.

**Comment by rdunk** [comment]
Oh great, that's good to know. Will be much more helpful for testing new features.

**Comment by chrismplus** [comment]
Is it possible to change the view link so that it goes to the Staging instance instead of Production? 

![image](https://user-images.githubusercontent.com/26731347/48992794-c0ec1d80-f174-11e8-81e0-98c15719fd74.png)

**Comment by rdunk** [comment]
Yep, should be done now.

Seems there are a few issues with the staging site from my end. I suspect the database is outdated, do you know if there was some specific version deployed for the new staging instance?

**Comment by erchaves** [comment]
Hi @chrismplus and @rdunk, I saw this ticket referenced from our asana board... Let me know how I can help here.

I'm still missing a little context about the stories project, so let me know if there is anything else I need to know.  Here are a couple notes:

The staging stories EC2 box is here: https://ap-southeast-1.console.aws.amazon.com/ec2/v2/home?region=ap-southeast-1#Instances:search=MPLUS%20Stories%20Staging;sort=instanceId

In the .env file, it seems we are pointing to staging values. So I'm not sure yet how it might be talking to the prod database, but I could look at the code more closely if it would be helpful. 
API_URL=https://staging-cms.mplus.org.hk

Another thing I don't know about is the DNS settings. I don't have access to the DNS account that controls what domain urls point to which aws boxes.

If it'd be helpful for us to put our heads together on this I'm happy to jump on a call as well.

**Comment by rdunk** [comment]
Preview button URL has been updated!

**Comment by chrismplus** [comment]
This issue seems to have resurfaced.

**Comment by micahwalter** [comment]
I think this should be resolved now that the staging CMS is looking at the right database. @chrismplus LMK if we can close this.

**Comment by micahwalter** [comment]
@chrismplus I can upload images in the CMS. What error are you seeing?

**Comment by chrismplus** [comment]
@micahwalter see below steps to reproduce: 

- Step 1: navigate to Wong Ping: Animating the Absurd under Channel > Episodes
- Step 2: navigate to the third tab 'Card', and upload a file
- Step 3: save and observe results on the front-end

Image: uploaded asset
![image](https://user-images.githubusercontent.com/26731347/51018227-ce892580-15b1-11e9-9fb7-03ff7109903b.png)

Image: front-end display on staging
![image](https://user-images.githubusercontent.com/26731347/51018237-d6e16080-15b1-11e9-9d82-c508961a7266.png)
