### ISSUE TITLE
YouTube footer links

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#225]
Hi @rdunk —

We'd like to create a link to our YouTube channel in the Stories footer. 

We have two channels for YouTube: 

TC: https://www.youtube.com/channel/UCLsE-cTgFvwXaZ8H0DsfOIQ
Eng: https://www.youtube.com/channel/UCA1jc0-yS4eFrF9WEAoa7Qg

Can we get the logo to link to the appropriate language channel based on the language the visitor is viewing the page in?

**Comment by rdunk** [comment]
Just implemented this locally, requires an extra field for the social media platforms for a TC link. The migration file will prepopulate the new field with the value from the current field, so no action required for the existing platforms. I'll add a new one for YouTube with the correct logo etc and this can use two different links. This will also give you the ability to add social media platforms for one language only if you so choose by leaving the relevant field blank.

Small point of clarification... the social media icons/links currently appear in three places: the footer, the "connect"/ 👋panel, and the "follow us on social media" sections on the homepage. For consistency these are all drawn from the same list, did you want YouTube to appear exclusively in the footer or can it also appear in these other locations too? Let me know and I'll push ASAP.

**Comment by chrismplus** [comment]
Thanks, Rupert. Let's have it appear in these other locations too.

**Comment by rdunk** [comment]
Great, deployed.
