### ISSUE TITLE
Instagram embed not working

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#226]
Hi @rdunk — we're unable to embed at the following IG URL (https://www.instagram.com/p/BquD3-uFxSn/) using the Instagram embed on the blog: 
![image](https://user-images.githubusercontent.com/26731347/49266039-96a9a100-f48f-11e8-92e5-d7f89cf0ba42.png)

It fails to render on the front end of the site. 

CC: @ellenoredsson

**Comment by rdunk** [comment]
Just pushed a fix for this. Were Instagram embeds ever working?

**Comment by chrismplus** [comment]
It's something I tested a long time ago and it was fine. We haven't used them for a while though
