### ISSUE TITLE
CMS: video authoring

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#23]
It would be preferable to insert a Brightcove ID number and let the platform take care of format conversation for the banner video element as opposed to uploading three separate files. 

![video-outputs](https://user-images.githubusercontent.com/26731347/31924343-054dd320-b8b3-11e7-819b-0eabb8bc150f.jpg)

**Comment by rdunk** [comment]
I had a look at the data we can grab from the Brightcove API and couldn't find any reference to snippets within existing videos themselves.

Can you confirm that you will be creating separate video entities on Brightcove to host these excerpts? Just want to check so we know what kind of data to expect.

I'll add this in as soon as I'm clear on exactly what we want to do here.

**Comment by chrismplus** [comment]
Correct. Video excerpts will be uploaded as individual files into Brightcove. 

Eg: Wong Ping
ID: 5623323289001

**Comment by chrismplus** [comment]
Moving to 'Ready'.

**Comment by rdunk** [comment]
Implemented, usage should be self explanatory. I've noticed however that Brightcove only seems to return MP4 files, do you have an example of an excerpt video with multiple formats?

**Comment by chrismplus** [comment]
@rdunk — I'm testing this integration with the Ho Fan video excerpt. I've verified it's working on: 

- Microsoft Edge
- Chrome
- Firefox
- Safari
- IE11
- Opera

Can you test on any other browsers that might fall back to an OGV or WEBM format?

**Comment by rdunk** [comment]
MP4 should cover the vast majority of browsers on recent versions of Windows and macOS. It's possible some Linux users might still encounter difficulties, I know WebM used to be the preferred format for Firefox users on Linux, this could no longer be the case though.

[This](https://caniuse.com/#search=mp4) would suggest MP4 should be fine.

**Comment by chrismplus** [comment]
This seems to be working fine. Thanks, @rdunk.
