### ISSUE TITLE
Podium publishing issue

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#231]
Hi @rdunk — I've left you a message on Slack about this with all the details. It would be great to prioritise this one. As I said—we've never encountered this issue before.

**Comment by chrismplus** [comment]
I've run a test creating a new article from scratch and experience the same result as outlined on Slack.

**Comment by rdunk** [comment]
Should be fixed now, moving to review,.

**Comment by chrismplus** [comment]
Thanks, @rdunk — confirmed it's working. Closing.
