### ISSUE TITLE
Outbound link iconography

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#237]
Hi @arnasziedavicius—

We think that the outbound links should consistently use the arrow iconography on the page. 

Eg: M+ Pavlion [arrow]
![image](https://user-images.githubusercontent.com/26731347/53383924-28a04780-39b4-11e9-94f3-9af76c5bd7b3.png)

Can we make this authorable from the CMS?

CC: @dianewang

**Comment by arnasziedavicius** [comment]
Please insert `class="external-link"` in `<a>` tags to add arrows to links. This allows to keep links without arrows as well:
![external-link](https://user-images.githubusercontent.com/5957816/53651774-47663e80-3c3f-11e9-80e4-3c40326b3759.png)
