### ISSUE TITLE
Webpage title and behaviour

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#238]
Can we update the webpage titles to read as follows:

- M+ Museum [when English is the selected language]
- M+ 博物館 [when Chinese is selected language]

This behaviour will mirror what's happening with the page titles on M+ Stories which updates depending on what language you have selected. 

CC: @dianewang

**Comment by arnasziedavicius** [comment]
Please note that **Holding** has been renamed to **M+ Museum** in CMS to utilise its translation option.
