### ISSUE TITLE
Page description in TC

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#239]
The description on the Traditional Chinese page still renders in English when the page is shared: 

![image](https://user-images.githubusercontent.com/26731347/53384668-b7ae5f00-39b6-11e9-9f67-8dc4cf09b34d.png)

Can we update this to the following: 

> M+，香港嶄新的當代視覺文化博物館

CC: @dianewang

**Comment by arnasziedavicius** [comment]
This description can now be updated in SEO tab under M+ Museum (previously Holding).
