### ISSUE TITLE
IE11 display issues

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#24]
Unexpected display state for all material that is not a 'banner' on the homepage when using IE11. 

Link: http://plus.zakgroup.co.uk/en

Please refer to attached screenshot for page render. 

![homepage-ie11-screenshot](https://user-images.githubusercontent.com/26731347/31932329-9e80c6fe-b8d8-11e7-8093-b64f5b55b976.png)

**Comment by rdunk** [comment]
This was down to a bug with the layout library we are using for the grid items. I've forked the repository and submitted a pull request here: ademilter/bricklayer#36.

Will use my forked repo until the pull request is merged.
