### ISSUE TITLE
Footnotes for multiple articles on the same page

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#242]
Hi @rdunk — there's an unforeseen formatting issue I'm coming up against for our upcoming Podium article. Please refer to the unpublished article within Issue 1 on the Production Site's CMS. 

This article will have multiple respondents, using multiple sets of footnotes. The CMS, however, doesn't know when once set of footnotes has begun or ended, so they're being grouped together under both articles. 

- Article A should have 6 footnotes;
- Article B should have 10. 

Currently, Article A and B are displaying each other's footnotes, so they're repeated twice (A and B each have 16 footnotes). 

Is there a way we can reset the count. i.e. once a footnote content block is inserted the count resets to 0 footnotes? Happy to hear if you have any other ideas on this too?

**Comment by rdunk** [comment]
I have this working on the `feature/footnotes` branch but I think it would be sensible to do some more testing before I merge it into staging. It basically works by looping through all the content blocks backwards, creating a new footnote group each time it sees a footnote block, and resetting the count. So I imagine something will go very wrong if a footnotes block is omitted and the article body contains footnotes.

Will get it tested and deployed to staging asap. When were you looking to publish the article?

**Comment by chrismplus** [comment]
Thanks, @rdunk — good to know there's a solution in the works. I'd like to start sending previews to the team for comment quite soon.

**Comment by chrismplus** [comment]
Hi @rdunk — just wanted to check in about this one. Is this in a position we can push to production soon?

**Comment by chrismplus** [comment]
Test

**Comment by chrismplus** [comment]
Hi @rdunk — this article is now in review. Can you let me know when we can push to production?

**Comment by rdunk** [comment]
I can get to this this week, but as we don't have a way to merge CMS changes into staging without committing to the master (production) branch it makes sense to wait until all these other changes around the new navigation are deployed.

**Comment by chrismplus** [comment]
Thanks, @rdunk — noted. Makes sense.
