### ISSUE TITLE
Stories-specific menu behaviour

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#249]
Some menu items in the universal nav dropdown, when viewing _Stories_ in Chinese, are linking to English language pages. This appears to only be happening on _Stories_, not the landing page. The items in question are highlighted in the image below. 

I can't see anything amiss in the CMS—do you have any ideas what this could be? Was wondering whether you had any insight from a _Stories_ perspective?

![image](https://user-images.githubusercontent.com/26731347/55147854-20d5ed80-5182-11e9-8100-a2961bf66fe1.png)

**Comment by rdunk** [comment]
@arnasziedavicius can you confirm if this is working on your local environment?

This function seems to be used for top level links, but they don't have an external_link property as far as I can see?
https://github.com/mplusmuseum/mplusmuseum-stories/blob/master/src/components/AppHeaderDropdown.vue#L155-L158

**Comment by rdunk** [comment]
@chrismplus is this one fixed now?

**Comment by dianewang** [comment]
@rdunk confirming that this looks good to us!
