### ISSUE TITLE
'View' button in staging CMS needs updating

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#256]
The 'View' button in the staging CMS is still linking out to the production site. We'll need it to link to the preview of the page on staging instead so we can preview pages easily. 

**Image:** 
![image](https://user-images.githubusercontent.com/26731347/58231764-55bd8580-7d6a-11e9-96a6-5bc53cb65c3a.png)

**Comment by rdunk** [comment]
I've updated this, I imagine it had reverted after the new environments were set up.

It's a little tricky to find so for future reference this can be updated in the CMS by editing the root page (M+ Stories), under the `Site Configuration` tab you'll find a field called `Website Base URL`.

**Comment by chrismplus** [comment]
Thanks, @rdunk—working as expected. Closing ticket.

CC: @dianewang
