### ISSUE TITLE
Newsletter subscription errors

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#258]
Hi @rdunk — visitors are currently unable to subscribe to the newsletter from Stories. I've found the following error message in the logs: 

![image](https://user-images.githubusercontent.com/26731347/58851136-1543fd00-86c4-11e9-8ba1-807cf0641c5e.png)

Can you help investigate?

CC: @dianewang

**Comment by rdunk** [comment]
@dianewang Is this one resolved now?

**Comment by dianewang** [comment]
Yes!  Thankfully it was the whitelisting error. It's now been resolved by our team.
