### ISSUE TITLE
Tags: design issue on mobile

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#27]
Blue tag border seems to have dropped off the mobile site. Please refer to screenshot. 

Tested on iPhone 5-6. The border is retained responsively on desktop however.  

![tag-border](https://user-images.githubusercontent.com/26731347/31980267-f17d1d76-b97d-11e7-8fa8-12140ea64838.jpg)

**Comment by rdunk** [comment]
Good catch. The line thickness was being rounded down to zero pixels by the looks of things. Fixed in phase 2.
