### ISSUE TITLE
Journal: image stacking on mobile

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#28]
Can we find a different solution for the mobile version of the 'small' mode of display for Journal content? Please refer to screenshot. 

![img_7798](https://user-images.githubusercontent.com/26731347/31980319-4b4db3ec-b97e-11e7-94fc-63d3d718c1ff.PNG)

**Comment by rdunk** [comment]
Should be updated in the latest prototype, text now wraps around the images.

**Comment by chrismplus** [comment]
@ellenoredsson -- please review when you have a moment.

**Comment by chrismplus** [comment]
Hi @rdunk -- just checking -- did we ever have an iteration of this where the images stacked full-width above the title? I assume the wrapping technique is to allow more articles to fit onto a mobile screen at a time?

**Comment by rdunk** [comment]
Not that I'm aware of. We thought it still important to retain the visual hierarchy of elements here.
