### ISSUE TITLE
Homepage: video tiles

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#29]
Videos that aren't part of a series lose the 'play' icon. It would be good to keep this as this clearly denotes 'video'. Can we include this icon for non-series videos? Please refer to screenshot. 

Videos tiles are currently unique in displaying tags outside of their containers. Can the container be expanded vertically (even if it's just an extension of the black gradient) to incorporate the tags?

![video-tiles](https://user-images.githubusercontent.com/26731347/31980382-af7f074e-b97e-11e7-97e5-0de3569b6524.jpg)

**Comment by rdunk** [comment]
Implemented, screenshot below. We've had to alter the gradient ever so slightly to create a seamless transition into the black, but I think it still looks good.

<img width="522" alt="screen shot 2017-10-31 at 11 47 36" src="https://user-images.githubusercontent.com/8467307/32222511-6fea3f88-be31-11e7-80af-c603cb2697db.png">

Feel free to close if satisfied.

**Comment by chrismplus** [comment]
@laramplus -- please review when you have a moment.

**Comment by chrismplus** [comment]
👍 this looks good @rdunk
