### ISSUE TITLE
Explore: search bar layout

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#30]
There are two actions competing with one another in the explore bar search field which when combined cause some confusion: 

1. _typing_ to explore
2. _clicking_ the suggested tag

The suggested tag works well on the homepage as it's not being combined with another action. Can we focus on the 'typing' to explore element in the search bar as this seems the most important thing to do with this element on this page. 

**Idea:** can "Explore content tagged with..." be typed out (animated) and the blinking caret placed at the _end_ of that phrase whilst the tag is removed?

![explore](https://user-images.githubusercontent.com/26731347/31980658-93b2daac-b980-11e7-956c-bb8526248900.jpg)

**Comment by rdunk** [comment]
Implemented in latest version, the text displayed is editable via the translations files. We can also edit the default text if required, let me know here if that's the case.

**Comment by chrismplus** [comment]
Thanks for this @rdunk -- @ellenoredsson and I reviewed the Arket site. We think the key difference is the drop-down state Arket offers once the search box has been activated--which we don't have on Explore. This helps orient the visitor and also provides context for the search. So for the Stories situation the simpler approach, while not as visually interesting, is clearer. 

Drop-down state:
![artket-dropdown](https://user-images.githubusercontent.com/26731347/32257835-534893e0-bef2-11e7-917f-d2c92501b029.jpg)

**Comment by rdunk** [comment]
Understood, thanks for providing feedback!
