### ISSUE TITLE
Journal: homepage tiles

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#31]
The Journal is now a lot more image-led as a section but this isn't really reflected in the tile design--perhaps it should be? Tiles with images feel like they'll be more enticing to click/tap into--as longer form content and on a slower publishing cadence it seems to make sense to better highlight this content through its homepage tile display? 

![journal-imagery](https://user-images.githubusercontent.com/26731347/31982262-88aa99e2-b98a-11e7-85e6-e096f8b34a17.jpg)

**Comment by rdunk** [comment]
Implemented in e87417aa969368ff9e280c926e7a1da5aa56d4b5. Images appear inset beneath the article excerpt.
