### ISSUE TITLE
Journal: consolidated feedback

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#32]
- **Most recent:** adding a “most recent” title seems like an important element to include to let a visitor know that what they are seeing on the landing page is the most recent content/article and that that is the organising logic of the what is on the landing page (rather than it being grouped by theme or issue). 

- **Imprint**: it’s important that we have a place on the landing page that details the imprint info (editors, editorial board, the frequency of publication, where based, and ways for readers to give feedback to the editorial board etc) as this will communicate clearly that PODIUM is an online publication. We also need to have a way to add an imprint section to individual issues in the event that there is a guest editor or guest editors for a specific issue. 

- **Ordering**: I’d like to confirm that all elements on the page can be ordered? So, “All Issues” can be moved up the page if necessary? An “Imprint” element could also be raised or lowered?

**Comment by chrismplus** [comment]
Hi @rdunk -- we think the way it's been implemented will satisfy the requirements for both the Podium landing page and issue landing pages. I'd like to test with real content--can you build out the authoring side of this?

**Comment by rdunk** [comment]
Will get this done today.
