### ISSUE TITLE
Asset fields in CMS

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#36]
Hi @rdunk -- there are a few fields in the CMS, mostly to do with assets such as videos or images, that have associated 'description' fields. I'm not sure what these fields are for? They don't seem to have a front-end display and they don't seem geared towards accessibility. 

Please refer to screenshot regarding video excerpt fields in the Episode section of the CMS. 

![text-fields](https://user-images.githubusercontent.com/26731347/31992273-65027600-b9ac-11e7-9ebd-772ca2522874.jpg)

**Comment by rdunk** [comment]
This is a built in property of the CMS 'file' fieldtype. It would be used for providing a title for a download link, for example. Currently the descriptor field for video assets is unused.

**Comment by chrismplus** [comment]
Noted, thanks.
