### ISSUE TITLE
Line break for secondary language

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#37]
@rdunk can we force a line break for the secondary language when only one character or word is fitting responsively on the screen? 

CC: @dianewang 

![title-line-break](https://user-images.githubusercontent.com/26731347/32031349-3698fa28-ba33-11e7-867c-ee61a7adf848.jpg)

**Comment by rdunk** [comment]
From a technical standpoint this is unfortunately just not possible due to the way inline elements are rendered.
