### ISSUE TITLE
Manual override for 'Recent' CMS list

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#38]
**Authoring/dynamic rules for 'Most Recent'.**

'Most Recent' will highlight the 20 newest pieces of content published on M+ Stories using the following content type quotas: 

- up to 8 blogs
- up to 5 journal articles
- up to 1 journal issue
- up to 5 videos
- up to 1 exhibition/commission

Content ordering: 
- is there a way for us to shuffle content type but not chronology?

Notes: 
- pagination is for the author to set (as is currently the case)
- the author can manually sort content after dynamic rules have been applied

CC: @dianewang @ellenoredsson

**Comment by rdunk** [comment]
We've implemented this with the following logic:

- The CMS grabs the latest 20 items using the criteria outlined above.
- It returns these 20 items in a random order to mitigate accidental grouping of one type of content.
- You can limit the number shown by default as with any other content list.

Let us know how/if we should tweak this to better suit how you imagined it. As mentioned before, we can't sort by dynamic and custom orders simultaneously, but could for example add the ability to always show the 4 (or some other number) most recent in order, and shuffle the remainder.

**Comment by chrismplus** [comment]
Hi @ellenoredsson @dianewang @laramplus -- let me know your thoughts on this... I think keeping the top three positions for the most recent would be good and support content that has a time-based prerogative. The quotas for content type and shuffle will keep the rest of the content from 'batching' up too much...

**Comment by chrismplus** [comment]
@rdunk -- let's implement as you suggest, but reserve the first three positions for 'most recent' regardless of content-type.

**Question:** is there any way to provide a manual override? This will be very handy, i.e. can we automatically generate a list that can then be ordered by the content author?

**Comment by rdunk** [comment]
Okay great, I will implement that for you to test.

And regarding the question: Yes, this would be quite complicated but technically possible. There would need to be some kind of manual action required to 'refresh/replace' the current list and we would probably need to build some quite complex logic to make it foolproof. I would suggest we keep this issue open at a lower priority and return to it after resolving some of the other issues.

**Comment by chrismplus** [comment]
Will test further on Production Site when we're dealing with final content.

**Comment by chrismplus** [comment]
Re-opening this one to deal with the manual override issue as discussed above.
