### ISSUE TITLE
Search bar blinking cursor should appear far left

### ISSUE THREAD

**Issue by laramplus** [mplusmuseum/mplusmuseum-stories#41]
Position of blinking cursor should be consistent for "Search" and "Explore" prompts (currently "Search" cursor is centered, "Explore" cursor is far left)
![stories search cursor explore](https://user-images.githubusercontent.com/26735115/32047102-8f35bf4c-ba77-11e7-846a-53586d24269d.JPG)
![stories search cursor issue](https://user-images.githubusercontent.com/26735115/32047104-8f6433fe-ba77-11e7-9ac3-b89fdce1a3b8.JPG)

**Comment by chrismplus** [comment]
Yes agree... "Search" should be left aligned in this case.

**Comment by rdunk** [comment]
The text in the input field would need to be fully left aligned for the cursor to appear to the left of the placeholder text. Happy to make the change, can you confirm that is preferable?

**Comment by chrismplus** [comment]
@rdunk with this being the case I think it makes sense to keep it as is for usability reasons. Aligning left in this instance would make the text more difficult to see, especially on mobile. @laramplus -- are you okay with this?

**Comment by chrismplus** [comment]
Closing issue.
