### ISSUE TITLE
Closed Captions not displaying

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#42]
Closed captions in TC and English have been added to the Brightcove console and are displaying when the video is viewed on Brightcove Video Cloud. They are not being drawn into the M+ Stories website, however. 

This error seems specific to Chrome. Attached is the console error. 

**Browser:** Version 61.0.3163.100 (Official Build) (64-bit)
**OS:** OS X El Capitan Version 10.11.6

**Console Error**
![no-cc-console](https://user-images.githubusercontent.com/26731347/32155097-3055e424-bd70-11e7-903f-bd5946ce37ab.jpg)

**Comparison with Brightcove dashboard**
![no-cc](https://user-images.githubusercontent.com/26731347/32155098-307ff3e0-bd70-11e7-9343-95f0c3387fb3.jpg)

**Comment by rdunk** [comment]
Is the issue here that CCs should be displayed by default, or that they're not showing at all even when toggled with the CC button?

**Comment by chrismplus** [comment]
@rdunk they are not showing even when the CC button is toggled.

**Comment by chrismplus** [comment]
Update: I have set all videos to automatically display TC captions. IE11 ignores this 'auto' setting and begins playing sans captions.

**Comment by chrismplus** [comment]
Closing this one. Will reopen if issue resurfaces.
