### ISSUE TITLE
Incorrect quotation marks

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#43]
Please refer to screenshot taken from a Channel _Series_ module. 

**URL:** http://plus.zakgroup.co.uk/en/channels/zhang-wei-fusuijing-building
**Browser:** Version 61.0.3163.100 (Official Build) (64-bit)
**OS:** OS X El Capitan Version 10.11.6

![incorrect-quotation-marks](https://user-images.githubusercontent.com/26731347/32155127-63647e70-bd70-11e7-9b2e-9b3f94272e54.jpg)

**Comment by rdunk** [comment]
Looks like this is an issue with the bolder version of the webfont We will contact the foundry to try and rectify. For the time being we have updated the styling to use the lighter weight for the quotation marks in this particular instance.
