### ISSUE TITLE
Blog: CTA element

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#44]
Unable to insert newsletter CTA into new blogroll--the authoring option is there but it doesn't display on the front-end.

**Comment by rdunk** [comment]
Ah yes, I was supposed to go over this in our last call, thanks for flagging.

As we are now moving to a unified CTA element for signups/social media (as shown in the latest iteration of the homepage), the fields in the CMS will need to be updated.

I would recommend the repeatable CTA field is replaced with a single input field (notice index) that corresponds to the position of the CTA element (i.e. insert after _n_ number of posts). The text for that will still be authorable via the CMS translations, but will be kept consistent for both the homepage and blog sections.

Can you confirm this is sufficient?

**Comment by chrismplus** [comment]
@rdunk -- just wanted to clarify the two points:

1. Automated insertion, i.e. after every 3rd post insert CTA. 
2. Current technique on the blog,

**Comment by rdunk** [comment]
1. I'd imagine this would just be one rather than repeated.
2. Yep, correct.

If you had some specific method for authoring these in mind feel free to outline it here and we can work out the required logic for it.

**Comment by chrismplus** [comment]
Hi @rdunk -- let's keep the same method that's currently in place on the Blog.

**Comment by rdunk** [comment]
Updated and simplified into a list of indices (i.e. insert after _n_ number of posts).
