### ISSUE TITLE
Blog image alignment

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#45]
Hi @rdunk -- keen to hear your thoughts regarding image alignment on the blog. I know a key element we wanted to push was the visuals by having them pop out of the text margins (as with the Journal)--but as it's only the right-hand side that breaks the text margin in gives the page a lopsided feeling. I think the visual weighting of the page would be improved if an image's right-hand margin aligned with the text margins. 

Thoughts? 

![blog-image-alignment](https://user-images.githubusercontent.com/26731347/32205234-195147a0-be29-11e7-8d30-6dbd1d440166.jpg)

**Comment by rdunk** [comment]
Implemented in 7fd74ee.

**Comment by chrismplus** [comment]
@rdunk I can't see this reflected on the front-end.

**Comment by chrismplus** [comment]
Yes, confirming images are displaying as expected. Closing issue.
