### ISSUE TITLE
Video: view more

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#46]
Wanted to touch base about this issue--we spoke previously about displaying related videos inside the video player upon completion of a video ala YouTube. 

![video-up-next](https://user-images.githubusercontent.com/26731347/32206158-738e65e0-be2e-11e7-88e6-2c24b0118759.jpg)

**Comment by chrismplus** [comment]
@rdunk -- looping back on this one.

**Comment by rdunk** [comment]
We _should_ be able to implement it independently. We just need to hook into an event that the player hopefully emits when a video ends... I'm hesitant to make alterations to the player until we've diagnosed some of the other Brightcove issues, as soon as we have some feedback on those I'll build this in.

Do we want the related videos logic to be the same as for other content types? i.e. finding from common tags.

**Comment by chrismplus** [comment]
I see, makes sense. 

I think the logic can something simple, like same series, _then_ all other video content. Thoughts?

**Comment by rdunk** [comment]
This makes sense. The other Brightcove issues seem to be pretty much resolved now so I'll get to work on this.

**Comment by rdunk** [comment]
I've implemented this in 0b580b226b02a0b11641fb270816fc64f8acbb8b for you to test. Let me know your thoughts and we can tweak as necessary.

**Comment by chrismplus** [comment]
Thanks for implementing @rdunk. 

Is it possible to approach the styling differently for mobile and desktop? I think for desktop it would be beneficial to: 

- Include title and duration of the video
- Remove the hover state and display title/duration up-front

We'll be adding more context—I don't see any downside to this. I notice YouTube have the same implementation we currently have, but they use auto-play. 

On mobile, displaying the title/duration will probably not be possible due to size constraints. The image alone, as it is currently, is probably more useful. 

Let me know your thoughts? Don't want to make this too complicated.

**Comment by chrismplus** [comment]
Moving to low-priority queue.
