### ISSUE TITLE
Microsoft Edge video: black bars

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#47]
Banner videos are letterboxed on IE. 

**Browser:** Microsoft Edge 41.16299.15.0
![ie-video-black-bars](https://user-images.githubusercontent.com/26731347/32207390-9256d4fa-be36-11e7-88a0-217da657ef54.jpg)

**Comment by rdunk** [comment]
We are using a polyfill to support object fit videos that seems to lack Edge support.

Waiting on this pull request that adds edge support: TricomB2B/object-fit-videos#9. Will use the forked repo as a dependency until the request is merged.

**Comment by chrismplus** [comment]
Hi @rdunk -- this issue is still occurring on **Microsoft Edge 41.16299.15.0**.
