### ISSUE TITLE
Banner image: crash

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#48]
If an image is uploaded in the "Banner Media Type" of an Episode in the CMS, the section (Channel) breaks. 

To recreate: 

1. Upload a new image to the Banner Media Type and save it. 
2. Go to the Channels landing page an observe results. 

**CMS view**
![banner-media-error](https://user-images.githubusercontent.com/26731347/32210431-84e42d56-be48-11e7-853a-117072259828.jpg)

**Console**
![banner-media-console](https://user-images.githubusercontent.com/26731347/32210367-34b0f968-be48-11e7-8203-900e42747ab8.jpg)

**Front end**
![banner-media-front-end](https://user-images.githubusercontent.com/26731347/32210517-eb5e5e8a-be48-11e7-85a4-48182509a07d.jpg)

**Comment by rdunk** [comment]
Thanks, fixed.
