### ISSUE TITLE
External link for Banner/Tile

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#49]
Can we append the 'external link' icon to pieces of content that live outside of M+ Stories? For use primarily in Online Exhibitions. 

**Tile**
![external-link-icon](https://user-images.githubusercontent.com/26731347/32211720-d18bd82e-be4e-11e7-8d50-a16b20b8f36c.jpg)

**Banner**
![external_link-banner](https://user-images.githubusercontent.com/26731347/32211732-daeeb3fa-be4e-11e7-9a83-c48cf95ecaf1.jpg)

**Ref**
![external_link](https://user-images.githubusercontent.com/26731347/32211748-e818c99e-be4e-11e7-8efd-9a53b0c1bbe6.png)

**Comment by rdunk** [comment]
Seems the best place for this would be alongside the section label for consistency. What do you think?

<img width="502" alt="screen shot 2017-10-31 at 10 58 54" src="https://user-images.githubusercontent.com/8467307/32220688-93607d1c-be2a-11e7-981c-3f1ae33b240f.png">

**Comment by chrismplus** [comment]
@rdunk Agreed. Looks good
