### ISSUE TITLE
Footnote Implementation

### ISSUE THREAD

**Issue by rdunk** [mplusmuseum/mplusmuseum-stories#51]
Current implementation of footnotes is quite straightforward from an authoring perspective, simply involves wrapping the footnote text in double curly braces at the specific position where the footnote should be inserted.

For example, the following text in the CMS:

> This is some text.{{This is a footnote.}} This is some more text.{{This is another footnote.}}

Will result in:

> This is some text.<sup>1</sup> This is some more text.<sup>2</sup>
> 1. This is a footnote.
> 2. This is another footnote.

Footnotes are shown in a consolidated list at the end of the text, the CMS will respect footnote ordering across multiple text fields in a single content matrix, all footnote numbers are automatically generated, so inserting a new footnote in between existing footnotes requires no other manual editing. Also note that the footnote feature is only available within content matrix fields.

Would be good to hear feedback once this has been tested with some actual content.

**Comment by chrismplus** [comment]
CC: @ellenoredsson this is how footnotes are created.

**Comment by chrismplus** [comment]
Thanks @rdunk -- this works quite well. We'll only have footnotes on the Chinese-language version of one of the articles which is currently in review. So we'll be able to test shortly.

**Comment by chrismplus** [comment]
Hi @rdunk — we have an instance with a reprint article where footnotes are denoted in Roman numerals. What is the best way to handle this using markdown?

**Comment by rdunk** [comment]
Hmm, two things to consider here. I would suggest that we keep the footnote style as consistent across articles as possible. I understand that you want to reproduce Reprints accurately, is this footnote style important to the content of the article? I would also argue that the order of these footer elements should be kept consistent across articles, especially as more than one article can appear in a single scroll.

Having said that, I do think footnotes should appear before they currently do, i.e. the sharebar should appear always as the last element. We could introduce an authorable 'footnote' block like we have an 'endnote' block, this would need to be added for footnotes to appear at all, but it would give you more flexibility in authoring. We could perhaps extend this so you could choose a footnote style (e.g. digits, roman numerals, etc), although again, I would advise against this unless it's absolutely necessary.

I would also suggest that the built-in footnote system using double curly braces is used over inline anchor tags, especially as we have multiple articles in a single scroll (it was built with this in mind and avoids naming conflicts). It also means that you can insert new footnotes if required without having to re-number all of the existing footnotes.

Let me know your thoughts, the options I've proposed shouldn't take too long to implement.

**Comment by chrismplus** [comment]
From @laramplus:

> First, I did a regular search with the words "From the Collection" - then from the blog post results view clicked into "Intervivos" but got redirected to "Seven Intellectuals." Back to the results view, I clicked the "From the Collection" tag from the blog post card. Two things happened: first, the tag led to "Explore" results with a bunch of collection based items (not just "From the Collection" category); then it led back to the Explore page, with no tag selected.

**Comment by rdunk** [comment]
Implemented in 64a009269cbc2cab501bb75562843b8f4042c144 and updated the hidden "Museums, Managers of Consciousness " article as an example.

**Comment by chrismplus** [comment]
Thanks, @rdunk — @amycmleung and I have tested this. Works well!
