### ISSUE TITLE
Dynamic generation of Issue # in Podium

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#52]
@rdunk -- unsure where the issue number is being generated? 

It's stuck at "3" as there was placeholder content in there previously. Can this number be reset or manually overwritten? 

**System generated Issue number:**
![podium-issue-number](https://user-images.githubusercontent.com/26731347/32259420-7bc15efc-befb-11e7-82ba-b6e02a213d73.jpg)

**Comment by rdunk** [comment]
This is determined by the sort order in the page tree, so if there are three issues called A, B and C:

> A = Issue 1
> B = Issue 2
> C = Issue 3

Reversing the order in the page tree would give you this:

> C = Issue 1
> B = Issue 2
> A = Issue 3

The reason we still include hidden issues in the count is that we didn't want hiding some issue to affect the others.

On second thought it may lead to less confusion if we have an input field for this. What do you think?

**Comment by chrismplus** [comment]
@rdunk yes, I think an input field would be good. I'm not so worried about the dynamic generation of Journal Issue numbers as the cadence will not be that demanding.

**Comment by chrismplus** [comment]
@rdunk -- has this one been implemented yet? The front-end is displaying as expected--but I can't see where to input Issue # in the CMS...

**Comment by rdunk** [comment]
Implemented. Should find a new field available when authoring an issue.
