### ISSUE TITLE
{author} functionality and author searches

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#54]
Currently, a search result for "Winnie Wong" doesn't return any results despite the fact she's an author of a Podium article: http://plus.zakgroup.co.uk/en/search?q=Winnie%20Wong 

I think this search term should return a result without the "author:" precursor?

**Comment by rdunk** [comment]
Agreed, implemented in 9df678243c73bc8908c00a467724b4b25c755ecb. The above link should now yield the relevant articles.
