### ISSUE TITLE
Author: bio display issue

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#55]
The biography input doesn't seem to recognise line breaks. Lars's bio consists of two paragraphs--the front-end of the site only draws in the second. 

Link: http://plus.zakgroup.co.uk/en/podium/issue-one-visual-culture/out-of-the-shadows-and-into-the-sunshine-a-reflection-on-the-contemporary-art-scenes-of-l.a-and-hong-kong

**Front-end display and CMS input disparity:**
![author-display-error](https://user-images.githubusercontent.com/26731347/32260602-dec38e28-bf03-11e7-829b-c1e2efdf67be.jpg)

**Comment by rdunk** [comment]
Thanks, was indeed ignoring line breaks. Implemented a fix, seems to be working now.

Closing, will keep an eye on it.
