### ISSUE TITLE
Broken homepage 🖥️🔨

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#56]
Homepage won't resolve on Staging... not sure what the issue is. The console isn't telling me much. I was authoring the Journal section last--other sections appear to be working. 

OS: OS X El Capitan
Browsers: Safari, Chrome, Firefox

**Error message recieved:**
![network-error](https://user-images.githubusercontent.com/26731347/32262165-1182b6d6-bf0e-11e7-9528-95883a686de7.jpg)

**Comment by rdunk** [comment]
Thanks for finding that, this was due to the existence of a Banner item that had no content selected. I've added an additional check so this should no longer happen.
