### ISSUE TITLE
Search filter labels

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#57]
Can we replace the term 'Episodes' with 'Videos'?

![search-filter](https://user-images.githubusercontent.com/26731347/32263893-ce9796b2-bf16-11e7-9694-edfaab652082.jpg)

**Comment by rdunk** [comment]
We can, although this would also update the labelling for all episodes across whole platform. Is that something you want to avoid?

**Comment by chrismplus** [comment]
@rdunk understood--let's change the term to "Videos" here and "Video" on the tiles for consistency.
