### ISSUE TITLE
Journal: loading states between articles (minor)

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#58]
Occasionally the 'Now View This' element is placed at the end of the page in-between articles. Once the user reaches that point on the page, it disappears. It creates the impression that the end of the page has been reached when in fact there are still multiple articles below. 

This issue only seems to occur when a specific issue is 'deep-linked' into, not when the page is navigated to via the Issue page. 

**OS:** OS X El Capitan
**Browser:** Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Steps to re-create:** 
1. Open a specific article: http://plus.zakgroup.co.uk/en/podium/issue-one-visual-culture/ive-been-waiting-for-you-for-a-long-time-visual-culture-and-the-pearl-river-delta
2. Scroll to the break between each of the articles on the page. 
3. Observe results.

**Comment by rdunk** [comment]
I agree this is unwanted behaviour. Added an additional check so the page won't render the suggested items component until after all the issue's articles have been rendered.

**Comment by chrismplus** [comment]
@rdunk the related content module no longer displays but the page still loads the footer element at the end of each article as it is scrolled down.

**Comment by rdunk** [comment]
I'm not sure we should hide the footer, but I have just added a more reliable method for preloading articles (8b9c7fb46d41add84879a03096f4b6a0567de59f) so the function that grabs the next article should be triggered earlier.
