### ISSUE TITLE
Related content: not everything can be searched

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#59]
Not all content appears to be searchable via the related content search field. 

**URL:** http://api.plus.zakgroup.co.uk/admin/page/edit/?id=2094
**Browser:** Chrome Version 62.0.3202.75 (Official Build) (64-bit)

**Failed search for James Kinoshita:**
![related-content-bug](https://user-images.githubusercontent.com/26731347/32267632-e4dd7f62-bf26-11e7-9c9e-ecb74d1db86f.jpg)

**Comment by rdunk** [comment]
Fixed!
