### ISSUE TITLE
Video player styling

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#60]
Video player styling appears inconsistent across the site. In all instances, the "M+ Stories" player has been selected via the CMS dropdown (which I assume is dynamically drawing the players in from Brightcove)? 

**URL:** http://plus.zakgroup.co.uk/en/channels/james-kinoshita-building-the-unanticipated
**CMS link:** http://api.plus.zakgroup.co.uk/admin/page/edit/?id=1834

**Player selection via CMS:** 
![brightcove-player](https://user-images.githubusercontent.com/26731347/32267934-f0c47b04-bf27-11e7-99ce-60902b1ca40f.jpg)

**Player's front-end display:** 
![video-player-styling](https://user-images.githubusercontent.com/26731347/32267994-2481d7ca-bf28-11e7-853d-6c971157e4c9.jpg)

**Comment by rdunk** [comment]
We are completely baffled by this one, too. Doesn't seem to be video or page specific, and happens seemingly randomly.

I am going to consolidate all of the issues we are having with Brightcove today so I can contact their support team. If you have a specific contact please forward me their details (I think you mentioned this wasn't the case), if not I'll just go use their standard support channels.

**Comment by chrismplus** [comment]
Here's how the videos generally appear on my mobile: 
![img-7839](https://user-images.githubusercontent.com/26731347/33062433-4363e0e0-ceda-11e7-8511-cc91f2c236b2.png)

**Comment by chrismplus** [comment]
Further information--warnings in the console when I get incorrect player styling:

**Browser:** Version 62.0.3202.94 (Official Build) (64-bit)
**Computer:** OS X El Capitan Version 10.11.6 *15G31) iMac

**Code:**
`2index.min.js:9 VIDEOJS: WARN: Component.extend({}) has been deprecated,  use videojs.extend(Component, {}) instead
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: videojs.util.mergeOptions is deprecated. Use videojs.mergeOptions instead.
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: The SocialButton component was added to the videojs object when it should be registered using videojs.registerComponent(name, component)
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: Creating a Button with an HTML element of div is deprecated; use ClickableComponent instead.
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: Setting attributes in the second argument of createEl()has been deprecated. Use the third argument instead.createEl(type, properties, attributes). Attempting to set role to button.
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: Setting attributes in the second argument of createEl()has been deprecated. Use the third argument instead.createEl(type, properties, attributes). Attempting to set aria-live to polite.
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: The SocialOverlay component was added to the videojs object when it should be registered using videojs.registerComponent(name, component)
k @ index.min.js:9
3index.min.js:9 VIDEOJS: WARN: this.options() has been deprecated and will be moved to the constructor in 6.0
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: Setting attributes in the second argument of createEl()has been deprecated. Use the third argument instead.createEl(type, properties, attributes). Attempting to set aria-role to dialog.
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: Setting attributes in the second argument of createEl()has been deprecated. Use the third argument instead.createEl(type, properties, attributes). Attempting to set aria-label to Sharing Dialog.
k @ index.min.js:9
8index.min.js:9 VIDEOJS: WARN: this.options() has been deprecated and will be moved to the constructor in 6.0
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: Access to player.bcAnalytics.client is DEPRECATED.
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: Access to player.bcAnalytics.history is DEPRECATED.
k @ index.min.js:9
index.min.js:9 VIDEOJS: WARN: Access to player.bcAnalytics.log is DEPRECATED.
k @ index.min.js:9
2players.brightcove.net/4697207075001/4ypydhsYl_default/index.min.js:9 VIDEOJS: WARN: Calling addRemoteTextTrack without explicitly setting the "manualCleanup" parameter to `true` is deprecated and default to `false` in future version of video.js
k @ players.brightcove.net/4697207075001/4ypydhsYl_default/index.min.js:9`

**Screenshot:** 
![image](https://user-images.githubusercontent.com/26731347/33119904-67af52dc-cfab-11e7-9f08-b43ac6cdea58.png)

**Comment by rdunk** [comment]
These are all warnings for the video player library that Brightcove uses (VideoJS) for features that are being phased out/replaced. They shouldn't affect the functionality of the player, thanks for adding regardless.

**Comment by rdunk** [comment]
@chrismplus — now that we've pushed everything to production, I'm actually having trouble replicating this. Seems that the player is consistently loading correctly. Will keep testing, please let me know if you come across this problem again.

**Comment by chrismplus** [comment]
@rdunk — I'm still noticing it. In particular, it always happens with this video: [https://stories.mplus.org.hk/en/channel/zhang-peili-gloves-and-messy-associations](https://stories.mplus.org.hk/en/channel/zhang-peili-gloves-and-messy-associations) 

The videos always load for me with the circular play button and the pink highlight on mobile.

**Comment by rdunk** [comment]
Looks like that particular video had the default player selected:

<img width="338" alt="screen shot 2017-11-24 at 16 49 11" src="https://user-images.githubusercontent.com/8467307/33218928-745b6a92-d137-11e7-994a-f88c0eeaacf1.png">

I've just updated it to the M+ Stories player. Was it just this video or others too on desktop?

Mobile sounds like it's definitely a problem though.

**Comment by chrismplus** [comment]
Moving this one to review. As noted in ticket #148, desktop styling no longer seems to be an issue.
