### ISSUE TITLE
Search results order

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#61]
Just wanted to get an understanding on how the default returned results were working. The sort by 'Type' seems like a double up with the filters in 'Show All Content'? We have a 'Sort by Oldest' option--does this mean the default method is 'Sort by Newest'?

**URL:** http://plus.zakgroup.co.uk/en/search?q=hong%20kong

![search-results-order](https://user-images.githubusercontent.com/26731347/32270561-5c20a9e6-bf31-11e7-8dc3-3a4f1bf2c920.jpg)

**Comment by rdunk** [comment]
Yep, default shows all content types, sorted by the date the page was last modified (newest first).

**Comment by chrismplus** [comment]
If this is the case should there be an additional filter that's just "Sort by newest"?

**Comment by rdunk** [comment]
Edited dropdown menus so the default option is now included in the options list.
