### ISSUE TITLE
Tagging: tag not displaying

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#62]
"👍" emoji is not being drawn into the front-end of the [Explore](http://plus.zakgroup.co.uk/en/explore) section. 

**URL:** http://api.plus.zakgroup.co.uk/admin/page/edit/?id=1851&s=1&c=1

**Back-end:**
![tag-not-displaying](https://user-images.githubusercontent.com/26731347/32306188-dc495090-bfb4-11e7-8477-7940b0a39b73.jpg)

**Front-end:** 
![tag-not-displaying-front-end](https://user-images.githubusercontent.com/26731347/32306216-03d63e34-bfb5-11e7-8c10-c1154490bde3.jpg)

**Comment by rdunk** [comment]
This is expected behaviour as the tag the "👍" is not assigned to any content. The front-end will only display tags that have been associated with content to prevent a single tag returning 0 results when exploring.

Please reopen if "👍" has been assigned to content and is still not appearing.
