### ISSUE TITLE
Journal: tags not displaying on article

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#64]
Tags are not displaying on the front-end of [Lars's article](http://plus.zakgroup.co.uk/en/podium/issue-one-visual-culture/out-of-the-shadows-and-into-the-sunshine-a-reflection-on-the-contemporary-art-scenes-of-l.a-and-hong-kong). They were displaying previously. I did unpublish, then republish the article, this might have been the cause. 

**Missing tags on front-end article display:**
![journal-tags-not-displaying](https://user-images.githubusercontent.com/26731347/32307223-5f68a2a0-bfba-11e7-92f3-f014f3474463.jpg)

**Back-end tag input:**
![journal-lars-tags](https://user-images.githubusercontent.com/26731347/32307237-6a7dd0a2-bfba-11e7-8c6d-951556e4ad7c.jpg)

Additionally, when the URL is input directly into the browser http://plus.zakgroup.co.uk/en/podium/issue-one-visual-culture/out-of-the-shadows-and-into-the-sunshine-a-reflection-on-the-contemporary-art-scenes-of-l.a-and-hong-kong, a "500 | Internal Server Error" is returned. 

**500 | Internal Server Error: Firefox**:
![journal-server-error](https://user-images.githubusercontent.com/26731347/32307315-ed060076-bfba-11e7-8ee2-e3d088daf113.jpg)

**Comment by rdunk** [comment]
Good spot.

Seemed to be caused when tags are trashed but not yet deleted, the CMS still stores the reference to the tag and was outputting it even though it was supposed to be hidden. I've added an additional validation check so this should no longer happen.
