### ISSUE TITLE
Podium: authoring

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#65]
I think we'll require a manual sorting field for the Podium landing page alongside the dynamic lists for greater control over the article content and how it's ordered. 

Side note: I'm unable to test this section with already published articles (I've tried unpublishing them then republishing, but this doesn't update the dynamic listing). 

**URL:** http://api.plus.zakgroup.co.uk/admin/page/edit/?id=1724

**Need to add manual list:**
![journal-podium-authoring-cms](https://user-images.githubusercontent.com/26731347/32307854-9b30e0e2-bfbd-11e7-8cb7-becb2b71d6e3.jpg)

**Comment by chrismplus** [comment]
Hi @rdunk -- I just wanted to loop back on this one for input.

**Comment by rdunk** [comment]
Implemented in d664259f6c9e471279ed648a451956b8cdd9424a.

New "Selected Articles" section with authorable title and articles.

**Comment by chrismplus** [comment]
Publishing the "Selected Articles" module returns a 500 | Internal Server Error. 

![image](https://user-images.githubusercontent.com/26731347/32528821-15d7a388-c470-11e7-8711-220d2a28f679.png)

**Comment by chrismplus** [comment]
No longer crashes the site.
