### ISSUE TITLE
Staging site broken from main link

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#66]
The only way to currently access the Staging Site is to open the following URL: http://plus.zakgroup.co.uk/, which returns a 404 error, but you can navigate to another page from that. 

Going directly to http://plus.zakgroup.co.uk/en returns a `500 | Internal Server Error`.

**Comment by rdunk** [comment]
This one is just down to our development server configuration, won't happen in the production environment.
