### ISSUE TITLE
Connect icon: show movement (low priority)

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#68]
Hi @rdunk -- can we see what this icon looks like with something denoting waving movement? Or a small animation showing movement (hand wave) when the visitor clicks. 

CC: @laramplus

**Comment by rdunk** [comment]
Added a hover animation in 481f835e12a3542a26f182ebdb3b04a440b5f7fb.

**Comment by chrismplus** [comment]
💯
