### ISSUE TITLE
Social Media: WeChat "Sharelink"

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#7]
Add "sharelink" for WeChat in Social Media Platforms element. SVG file and hover colour have been created.

**Comment by rdunk** [comment]
Can you give me some more info on this one? I uploaded a new logo to the CMS which is also available in this repository, see below:

https://github.com/mplusmuseum/mplusmuseum-stories/blob/master/src/assets/img/social-wc.svg

**Comment by chrismplus** [comment]
We need to provide sharing links for the CMS fields. I'm not sure what these should be for WeChat...

**WeChat CMS:**
![image](https://user-images.githubusercontent.com/26731347/32815469-37df871e-c9ef-11e7-9eb0-e3a157e93514.png)

**Twitter CMS (for comparison):**
![image](https://user-images.githubusercontent.com/26731347/32815498-563fd51a-c9ef-11e7-9e1c-785f832d7aa6.png)

**Comment by rdunk** [comment]
Understood. I'm afraid my knowledge of WeChat is pretty limited and finding some conflicted answers on Google about this. Is there an example website that has WeChat share links you could provide a link to?

**Comment by chrismplus** [comment]
Hi @rdunk -- I've looked into this with @dianewang -- it feels like the best option is a desktop-specific QR code share. Have a look at this NYT article for an eg. It's basically a hover state that reveals a QR code. 

Ref: https://cn.nytimes.com/opinion/20171116/chinese-communist-party-xi-jinping/zh-hant/ 

˙˙˙ʞuᴉɥʇ noʎ ʇɐɥʍ ǝǝs

**Comment by rdunk** [comment]
Doesn't seem to work for anyone here, just see a popover with a loading spinner. Will check back.

**Comment by chrismplus** [comment]
Yeah, it's basically that. A popover--but it should load a QR code...

**Comment by dianewang** [comment]
Hi @rdunk here's a different example, but it's in Chinese. On the right-hand side, floating near the scrollbar is share section - if you click on the WeChat icon it will load a QR cod there. Let me know if that works as an example!

**Comment by dianewang** [comment]
I apologise, forgot the link: https://baike.baidu.com/item/%E5%A5%A5%E5%8F%A4%E6%96%AF%E7%89%B9%C2%B7%E7%BD%97%E4%B8%B9

**Comment by rdunk** [comment]
Ah, I think I understand the implementation.

Looks like the QR code is just an encoding of the website URL, I'm assuming the WeChat app has an inbuilt QR code scanner that you use to share this content?

How should the share function work on mobile devices?

**Comment by chrismplus** [comment]
@rdunk we're thinking that this is a _desktop-only_ feature. Native browser share options will cover mobile sharing.

**Comment by dianewang** [comment]
@rdunk That is correct on the functionality! Typically WeChat users scan within the app as opposed to with the camera (of course, that may well change in the near future as iOS and Android apps have started reading QR codes in camera..)

Most web experiences have struggled to create a very good WeChat share function on mobile devices, as typically many users are within the app already, or utilising a native app -- which is one of the few scenarios that you can initiate a direct share to open within the WeChat app.

**Comment by rdunk** [comment]
Great, implemented in 413a647d6f91b7365eb97854bd18166315528fdd and live in production and on the development server. Let me know if that meets requirements.

**Comment by chrismplus** [comment]
Hi @rdunk -- @dianewang and I have had a look at this. The QR code is working as expected on the native iOS camera, but not within WeChat itself. 

Two other things we've noticed: 

- On PC's the whole browser window does a slight shift when the QR code animates in. 
- Once the QR code has animated onto the page, the cursor changes to a zoom-out icon.

The animation, and look and feel of this is great though.

**Comment by rdunk** [comment]
Looks like WeChat doesn't like when the QR code is lighter than the background (inverted). Will push a fix shortly.

**Comment by rdunk** [comment]
Inverted and tested working on WeChat app 5361fab15dd118a44ed7b165e9d24b479bb94f58.

Is the shift due to the disappearance of the scroll bar on PC? Can you confirm if the same behaviour happens when viewing an image in lightbox mode?

**Comment by chrismplus** [comment]
I'll need to test in the office tomorrow. Regarding the second point, can the cursor remain as per normal instead of changing to the zoom-out cursor?

**Comment by rdunk** [comment]
Sure, can implement that.

**Comment by rdunk** [comment]
Removed cursor in c04fd0411edd5017e95f3ea742acfb46108c6f8b. Will leave open until shift issue is resolved.

**Comment by chrismplus** [comment]
**QR code appears fullscreen in Firefox:** 
![image](https://user-images.githubusercontent.com/26731347/33156481-11883c7c-d035-11e7-94ed-b0a8baffb9d9.png)

**Comment by chrismplus** [comment]
The 'jump' issue can be replicated in Browser Stack. We can't see what might be causing this...

**Comment by rdunk** [comment]
Although I kind of like the huge QR code visually... it is definitely a bug, so fixed in f624be4e75a210f68919cad3a3c2c9a8cf467fa7!

Shifting bug also fixed in f8b7be9a6ae27d25d5124b67c397baad9a9357af. This was down to trying to prevent scrolling when the QR code element is active, but we've removed this as it's not strictly necessary. Seems to resolve the issue.
