### ISSUE TITLE
Pillar-boxed video on banner element

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#70]
Video is pillar-boxed on Microsoft Edge inside the banner element. 

This case actually seems to be unique across all video--most other videos are letterboxed--so it might have to do with the actual video output itself? 

**Browser:** Microsoft Edge 41.16299.15.0
**URL:** http://plus.zakgroup.co.uk/en/channels

**Pillar-boxed video:** 
![pillar-boxed](https://user-images.githubusercontent.com/26731347/32316687-36116b30-bfec-11e7-8bd5-b94f83ad381c.jpg)

**Comment by rdunk** [comment]
Strange, I added a fix for this earlier in the week. See below, on exactly the same version of Edge on Windows 10.

This was happening if the video dimensions were smaller than the viewport dimensions, but I can't seem to replicate it any more.

<img width="1990" alt="screen shot 2017-11-02 at 09 48 31" src="https://user-images.githubusercontent.com/8467307/32319619-1e95352e-bfb3-11e7-97d4-2a8e31b3d50d.png">

Any errors in the console when you visit this page?

**Comment by chrismplus** [comment]
No errors in the console. I'm running Windows through Remote Desktop, but @angelmplus is getting the same error on Windows 7. I have a feeling it might be specific to the video output in this case. But it's strange that it's running correctly on your instance...

**Comment by chrismplus** [comment]
Okay--just tested with the Wong Ping excerpt and it's behaving as expected. I think it has to do with the resolution of the video output. I'll re-output and see how it goes. Closing issue for now, will reopen if necessary.

**Comment by chrismplus** [comment]
Bumped up the resolution to 2000px across and that seems to have [done the trick](http://plus.zakgroup.co.uk/tc/channels).
