### ISSUE TITLE
Nav: header behaviour

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#71]
The more I browse the site, the more I find myself clicking on the nav bar header text (see screenshot below) with the expectation that it take me to the top of whatever I'm browsing. I think implementing this as a universal feature across the site would be handy, a quick 'back-to-top' shortcut. 

Can we implement this so that's the case? 

![nav-bar-link](https://user-images.githubusercontent.com/26731347/32316748-77c24068-bfec-11e7-8ab1-9573e70f76c0.jpg)

**Comment by rdunk** [comment]
I've just implemented this as I understood it but then re-read your comment and think I may have misunderstood.

Clicking should take you back to the top level section page (this is what I've built) or to the top of the current page?

**Comment by chrismplus** [comment]
Hi @rdunk -- the nav headers aren't currently linking anywhere on my side, but let me elaborate on the desired functionality: 

- Clicking on the header should basically be considered as a 'back-to-top' function. 
- In a Podium article, a click on the header will take to back to the top of the article. 
- On the Channel landing page, a click on the header will simply take you back to the top of the overall page. 

Let me know whether this is clear?

**Comment by chrismplus** [comment]
****Update:** the headers are linking now. The current functionality is not desired outcome. 

Clicking on: Podium: Visual Activism and the Snapchat Generation, at this point on the page...
![image](https://user-images.githubusercontent.com/26731347/32368596-38f66f0a-c0c1-11e7-9fe7-d292272177d8.png)

...should take me back to the top of this particular article: 
![image](https://user-images.githubusercontent.com/26731347/32368635-5fa9aafe-c0c1-11e7-9dc5-4f9ee2aaa25f.png)

**Comment by rdunk** [comment]
Implemented!
