### ISSUE TITLE
Tile labelling

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#72]
- Can we call the current "Article", "Podium Article"?
- Can we call the current "Issue", "Podium Issue"?
- Can we call the current "Online Exhibition", "Interactive"?

CC: @ellenoredsson

**Comment by rdunk** [comment]
These are all authorable in the CMS via the translation files, specifically the "content" file. The defaults are below but can be easily overridden:

- Article
- Articles
- Video
- Videos
- Online Exhibition
- Online Exhibitions
- Journal Issue
- Journal Issues
- Blog Post
- Blog Posts
- Page
- Pages
- Information Page
- Information Pages

**Comment by chrismplus** [comment]
@rdunk updating the "content" file doesn't seem to have any effect on the front-end.

Ref: http://api.plus.zakgroup.co.uk/admin/setup/language-translator/edit/?language_id=1018&textdomain=site--templates--translations--content-php

![updated-tile-cms](https://user-images.githubusercontent.com/26731347/32319215-b94535f6-bff4-11e7-977e-9e52e007dbe3.jpg)

**Comment by rdunk** [comment]
Most likely the data was cached so hadn't updated for you. Reopen if this persists but tested working here.

**Comment by chrismplus** [comment]
I see. @rdunk -- is there any way that we can manually refresh the cache?

**Comment by rdunk** [comment]
@chrismplus Yep, just save any page in the page tree. Sorry if I didn't make this clear before. We can look into implementing a dedicated button somewhere if that would be useful.

**Comment by chrismplus** [comment]
@rdunk this is my page-tree view. I can't see an option to save at this level--unless I'm missing something? 

**Page tree view with my credentials:**
![image](https://user-images.githubusercontent.com/26731347/32367485-3ee6c21a-c0bd-11e7-9c14-5afafc2fcd29.png)

**Comment by rdunk** [comment]
Ah, I just mean any page (i.e. not a translation file or something like that), but yes, you're correct that you can only save from an individual page view.

Also, it looks like you're using the old admin theme, is that by choice? I find the other one a lot easier to use.

**Comment by chrismplus** [comment]
I didn't realise we could change admin themes... is the one that you use called Reno? 

![image](https://user-images.githubusercontent.com/26731347/32421883-387c456e-c2d7-11e7-8406-d51101ab4577.png)

**Comment by rdunk** [comment]
Yep, I've switched you over.

Feel free to change it back via Access > Users if you prefer the other one!
