### ISSUE TITLE
IE 11: text alignment on homepage

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#73]
"Connect" and "Sign up" calls to action on the homepage are misaligned on IE11. 

**URL:** http://plus.zakgroup.co.uk/en
**Browser:** IE 11.15.16299.0

![connect-text-ie-11](https://user-images.githubusercontent.com/26731347/32319592-136b352a-bff6-11e7-9426-6f71f4be6e0b.jpg)

**Comment by rdunk** [comment]
Alignment issue seems to be an IE specific bug when using flexbox layouts. Implemented a fix.
