### ISSUE TITLE
"Un-pinning" post in Blog breaks site

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#77]
**To recreate:** 
- navigate to the _Five Things To Look For When Watching San Yuan Li by U-thèque_ blog in CMS. 
- un-pin post and save the page. 
- observe results. 

**URL:** http://api.plus.zakgroup.co.uk/admin/page/edit/?id=1470&s=1&c=3

**Un-pinning the following post causes the entire site to return a "503" error:** 
![image](https://user-images.githubusercontent.com/26731347/32367749-27f427cc-c0be-11e7-9411-ebb7b90d9c69.png)

**Comment by rdunk** [comment]
I'm not able to replicate this. 503 would suggest it's a server error (e.g. server overloaded). Were you seeing the error on the front-end or back-end?

**Comment by chrismplus** [comment]
I can no longer replicate this either. It was appearing on the front-end of the site. The CMS was behaving as normal. I'll close this one for now but will keep an eye on it.
