### ISSUE TITLE
Exhibitions URL structure

### ISSUE THREAD

**Issue by rdunk** [mplusmuseum/mplusmuseum-stories#78]
As the terminology has changed for the exhibitions section, should this be reflected in the URL structure?

**Comment by chrismplus** [comment]
Yes please

**Comment by chrismplus** [comment]
Hi @rdunk -- this is still displaying as "exhibitions" on Staging URL structure. 

![image](https://user-images.githubusercontent.com/26731347/32528561-a7138198-c46e-11e7-97f9-b42289306e98.png)

**Comment by rdunk** [comment]
Staging server wasn't updated, working now.
