### ISSUE TITLE
Journal: pull quotes

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#79]
Having authored the Journal with actual Podium content I think we should reinstate the two pull quote styling options. There are times when we have few images to choose from, and a pull quote would help with the spacing of a page. 

Pull quote stylings:
![image](https://user-images.githubusercontent.com/26731347/32479879-d7762140-c3c6-11e7-88a4-45df6ee18d6c.png)

![image](https://user-images.githubusercontent.com/26731347/32479890-ea565f6e-c3c6-11e7-8600-4a84bd51e8d8.png)

**Comment by rdunk** [comment]
Implemented the second option in a5fb863faa5e166a12b742693f87c2942d3dd781.
Also see issue #85. This is a site wide style so can be used in all sections where configurable content blocks are available.

**Comment by chrismplus** [comment]
Hi @rdunk -- I can't see how to add a pull-quote to an article. The <blockquote></blockquote> styling renders the text grey.

**Comment by chrismplus** [comment]
Thanks!

**Comment by chrismplus** [comment]
Hi @rdunk -- it's just come to my attention that we don't allow for italics for Chinese text in our style guide. Can we have a specific Chinese-language pull quote?

**Comment by rdunk** [comment]
I think we might be better off using a bold style for the quote section for both English and Chinese. Thoughts?

<img width="863" alt="screen shot 2017-11-14 at 17 12 07" src="https://user-images.githubusercontent.com/8467307/32793839-fbafdc84-c95e-11e7-9d64-30467a2481f6.png">

**Comment by chrismplus** [comment]
@rdunk hmmm... I'm not sure. Here's how it's looking in situ:

**Pull quote:** 
![image](https://user-images.githubusercontent.com/26731347/32815609-d4a08b84-c9ef-11e7-8f3f-d79810cb7725.png)

**URL:** https://plus.zakgroup.co.uk/tc/podium/issue-1-visual-culture/on-smallness-in-hong-kong-art

Maybe it needs quotation marks? It's not fitting in seamlessly for me at least. What do you think?

**Comment by rdunk** [comment]
Gotcha, how about centred text?

<img width="835" alt="screen shot 2017-11-15 at 18 06 41" src="https://user-images.githubusercontent.com/8467307/32852542-2c8768e6-ca30-11e7-968c-b41cb51e7e50.png">

**Comment by chrismplus** [comment]
I think that works well here. Can we keep the existing alignment in Channel though? 

So, basically two pull-quote styles: Channel/Podium?

**Comment by rdunk** [comment]
New implementation in d896e2237df489f04c76d4678f1fbd1953293976.

Quotes are available to add in all sections and appear left aligned, excluding in Podium articles where they appear centred.
