### ISSUE TITLE
Blog: nav bar header

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#80]
I'm splitting this issue out from [#26](https://github.com/mplusmuseum/mplusmuseum-stories/issues/26) as I think this would be good to implement for the new blog display. On desktop: can we append blog title to the section title in-line with what's happening in the Journal? 

**Journal nav bar menu behaviour:**
![nav-bar-link](https://user-images.githubusercontent.com/26731347/32534329-11a6ac80-c490-11e7-97c5-35e3377c6205.jpg)

**Comment by rdunk** [comment]
Added in 92e64217dfe5088fc671778f2095d13e9c12f40e. Only triggered when viewing multiple blog posts on a single page.
