### ISSUE TITLE
Blog: tag alignment

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#82]
The tag with the ellipsis is misaligned on iOS in both Safari and Chrome. Please refer to screenshot below. 

![img-7822](https://user-images.githubusercontent.com/26731347/32584943-e1003afa-c535-11e7-9223-1f86546c6494.jpg)

**Comment by rdunk** [comment]
Thanks. Fixed in #e171530c0a1a915b0c70ed2ca519394a820e6721.
