### ISSUE TITLE
Channel: block quote

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#85]
Hi @rdunk -- this is a low priority -- we have already created a series of blockquotes for the Channel videos -- we had a special styling for this in the previous iteration of the site -- it would be good to include on the new pages too. 

Old design: 
![image](https://user-images.githubusercontent.com/26731347/32597028-564039f2-c570-11e7-8140-e9115c5f24ff.png)

**Comment by rdunk** [comment]
Implemented in a5fb863faa5e166a12b742693f87c2942d3dd781.

**Comment by chrismplus** [comment]
Unable to create in Channel.

**Comment by chrismplus** [comment]
Thanks!

**Comment by chrismplus** [comment]
Hi @rdunk -- it's just come to my attention that we don't allow for italics for Chinese text in our style guide. Can we have a specific Chinese-language pull quote?
