### ISSUE TITLE
Microsoft Edge: connect dialogue box

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#86]
Social media icons are rendered in white instead of blue. 

Also, please note the behaviour of the arrow and the cross once you start entering text into the newsletter subscribe field. 

**Browser:** Microsoft Edge 41.16299.15.0

**White icons/overlapping arrow and cross:**
![connect-dialogue-box](https://user-images.githubusercontent.com/26731347/32645365-f019af5c-c621-11e7-88c4-a3ab4783dbd2.jpg)

**Comment by rdunk** [comment]
Now using a new implementation (f8e5130c2e495792a836719a83ea0847e508b663) for SVG icon colourisation. Tested working on IE11/Edge14+.

Also pushed a fix for removing the non-standard clear button 505ec235f7ea924f696cc377544e6a75226b2446.
