### ISSUE TITLE
Video embed alignment issue: Journal

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#87]
Video embed (YouTube) can't float left or right in Journal article. 

**URL:** https://plus.zakgroup.co.uk/en/podium/issue-1-visual-culture/on-smallness-in-hong-kong-art

![image](https://user-images.githubusercontent.com/26731347/32651933-96ca992c-c63d-11e7-9dbe-5747108f44d8.png)

**Comment by rdunk** [comment]
Noted, will implement a fix for this.

**Comment by rdunk** [comment]
Fixed in d81ea326d25c7381abfb042f6df20ed5728daea7.
