### ISSUE TITLE
Channel URL issue

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#88]
Channel is incorrectly labelled as 'Channels' in the Production CMS. When this is updated to Channel all Episode previews and landing pages are unable to be previewed on ZG Dev. 

**Incorrect naming:** 
![image](https://user-images.githubusercontent.com/26731347/32686024-0b5b0c14-c6d8-11e7-8ada-956ec56cdb31.png)

**Comment by rdunk** [comment]
The top level section URLs should not be altered as the front-end will not be able to query the CMS for data. Also please note these have no bearing on the front-end URL structure. I can update the front-end URLs if required but those changes need to be built into the app.

Will update /channels/ to /channel/ and close when implemented.

**Comment by rdunk** [comment]
Implemented in c2756c06eda6d4e67e1a5ed7818953b6902cdc51. Also updated all corresponding references in CMS. Testing working, pushed to production.
