### ISSUE TITLE
Unable to edit English translation files 

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#89]
Only three English translation files appear under 'Site Translation Files':  

Only three .php files are available to edit; "content" is missing for example:
![image](https://user-images.githubusercontent.com/26731347/32708382-8614bdb4-c864-11e7-98b8-679fb3909488.png)

There are more options for site translation files when 'Traditional Chinese' is selected. 
**Ref:** https://cms.mplus.org.hk/admin/setup/languages/edit/?id=1020

**Comment by rdunk** [comment]
Thanks, these just need to be added as required via the CMS. I've added all custom translation files for English now.
