### ISSUE TITLE
CMS: authoring lock

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#9]
**Issue:** If someone is editing a page it should be locked to prevent the creation of different 'versions' of the page. 

**Expected behaviour:** Allow a notification, or page-lock if an author is making edits to a page in the CMS.

**Actual behaviour:** No notification is given to authors about who is editing a page at a given time.

**Comment by chrismplus** [comment]
@rdunk -- I'm moving this to the _ready_ column. Not having this in place is causing some issues--i.e. changes are being recorded over the top of one another if more than one person is logged into a page.

**Comment by rdunk** [comment]
This has been added, you'll now get a red warning notice if a page is currently being edited (or has been edited in the past 60 seconds) by another user. We can also enforce a 'hard lock' if preferred.

**Comment by chrismplus** [comment]
Thanks, @rdunk -- this has made out day
