### ISSUE TITLE
Journal: unable to stack images when floating left/right

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#90]
**Expected behaviour:** images should stack on top of one another is position one after another and aligned to the same side. 

CMS view: 
![image](https://user-images.githubusercontent.com/26731347/32709392-0f7a4924-c86b-11e7-9f65-82cfce993819.png)

Front-end view:
![image](https://user-images.githubusercontent.com/26731347/32709402-1beb37d6-c86b-11e7-8930-8ec341caa448.png)

**Comment by rdunk** [comment]
Implemented in d81ea326d25c7381abfb042f6df20ed5728daea7. Should work as expected now using your example above. As discussed, captions appear alongside their respective images by default.
