### ISSUE TITLE
Podium: side-by-side image layout

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#91]
Hi @rdunk -- when you try and author two images alongside side each other (sharing a row--float left/right), the display is a bit glitchy. Notice how the text in the next paragraph down reacts. I've attempted to add in some HTML linebreaks without any luck. 

![side-by-side](https://user-images.githubusercontent.com/26731347/32712661-c1d85394-c880-11e7-8189-7a6144b60ddc.jpg)

I think this will need to be a necessary display option moving forward--it would be good if they could share the image description field as well in such a case--as having both images needing their own description field looks slightly odd on mobile.

**Comment by rdunk** [comment]
Thanks. Implemented in d81ea326d25c7381abfb042f6df20ed5728daea7.

To display two media blocks side by side, **float the first block left** and the **float the second block right**. Any following text should now clear both blocks and show text as expected.

Please close when tested and satisfied!
