### ISSUE TITLE
Homepage: unable to create content list based on a tags

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#92]
Hi @rdunk -- we discussed this a while ago. A content list based on a specific tag will be really helpful in homepage listings. 

**Missing add by 'tag':** 
![image](https://user-images.githubusercontent.com/26731347/32717608-30dd1612-c895-11e7-893a-877c59984130.png)

**Comment by rdunk** [comment]
This one is ready to go, just need to confirm whether you want an AND or OR implementation for multiple tags.

AND: Content returned must have **all** of the selected tags.
OR: Content returned will have **one or more** of the selected tags.

**Comment by chrismplus** [comment]
@rdunk -- is it possible to have both options? 

If not, the second option, "Content returned will have one or more of the selected tags" would be preferable.

**Comment by rdunk** [comment]
Implemented both with a toggle to choose the preferred option.

Also added an example (currently hidden) as the last element for you to check out, feel free to delete it.
