### ISSUE TITLE
Flipped hand-wave?

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#93]
Hi @rdunk -- was the hand flipped horizontally deliberately?

**New orientation:**
![image](https://user-images.githubusercontent.com/26731347/32761683-ad7927ac-c92f-11e7-8565-3044d96ef42b.png)

**Comment by rdunk** [comment]
Oh dear, looks like it reverted to an old iteration, fixed in c6f603463ae1174b02bc76b68d45658916e16201.
