### ISSUE TITLE
Filled in 'play' and 'duration' iconography

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#94]
Hi @rdunk -- I've noticed that the play and duration icons that overlay on video content, most noticeable on a banner element, has been filled in now? Just checking that this was deliberate? It seems new??

![image](https://user-images.githubusercontent.com/26731347/32761707-c666edee-c92f-11e7-9b82-e262859864d4.png)

**Comment by rdunk** [comment]
Not deliberate! Fixed in 56af51f94e5f60faf273983498237275303d7351.
