### ISSUE TITLE
Caching issue: Channel episodes

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#95]
Hi @rdunk -- there's an unexpected image caching issue at the moment on the Channel episode pages. 

**Steps to recreate:** 

1. Visit: https://plus.zakgroup.co.uk/en/channel/zhang-peili-gloves-and-messy-associations
2. Note the image below the text. 
3. Visit another page from the "Part of the series “Inside the M+ Sigg Collection”" links. 
4. Note the image below the text. 

You'll see it's not refreshing the image. Each of these five episode pages has unique images associated with them. 

Refreshing the page will show you the image that's meant to be displayed.

**Comment by rdunk** [comment]
Good catch, looks like the app wide image component was not reacting to changes when navigating between routes using the same view. Fixed in e042b59479fffba75e325283d5c5b88aa03a52c9.
