### ISSUE TITLE
Image ratio stretched in "Now View This"

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#96]
Images are being stretched in the _Now View This_ element:

![image](https://user-images.githubusercontent.com/26731347/32765059-bf0da448-c943-11e7-9598-8ddccc4b7965.png)

**Comment by rdunk** [comment]
Wow, not sure how I didn't notice this one before!

Fixed in 14ab5bb7ff5a9296562b13ad685883ef3979d80a.

**Comment by chrismplus** [comment]
Me too. I think it must have been introduced recently.

**Comment by chrismplus** [comment]
This change is working on https://plus.zakgroup.co.uk/en/ but not https://stories.mplus.org.hk/en/blog yet? Is this expected?

**Comment by rdunk** [comment]
Yep that's correct, change hasn't been pushed to production yet.
