### ISSUE TITLE
Blog: leading media cache issue

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#97]
Leading media is not being refreshed when a new blog post is launched from the 'Now View This' section. 

**Browsers:** all
**To recreate:** 
1. Visit: https://stories.mplus.org.hk/en/blog/from-the-collection-hong-kong-inter-vivos-film-festival-by-ho-sin-tung
2. Navigate to the bottom of the page and click on one of the related pieces of content. 
3. When the new page loads note the leading media. 

**Leading media is not being refreshed:** 
![blog-image-cache](https://user-images.githubusercontent.com/26731347/32765021-85b32628-c943-11e7-831e-2041f8501620.jpg)

**Comment by rdunk** [comment]
Same as #95.

Fixed in e042b59479fffba75e325283d5c5b88aa03a52c9.
