### ISSUE TITLE
Channel: links not resolving correctly

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#98]
**Steps to recreate:** 

1. Visit: https://plus.zakgroup.co.uk/en/channel
2. Right click on and open a new tab for each of the _Making Hong Kong_ videos. 
3. Visit each of the tabs and note the results. 

When I follow these steps, some of the pages resolve. 
![image](https://user-images.githubusercontent.com/26731347/32765538-e1e7a462-c945-11e7-823a-899c29365483.png)

Some pages return the following: 
![image](https://user-images.githubusercontent.com/26731347/32765592-224e8188-c946-11e7-8124-84b5ce89b047.png)

Console view: 
![image](https://user-images.githubusercontent.com/26731347/32765603-31ea82f4-c946-11e7-86d5-78163b42a6f9.png)

**Comment by rdunk** [comment]
Thanks for noticing that. Was an underlying problem with the way the language was being set each time the app was loaded. I've pushed a commit 13c517ab349077ebd593e69630f34e02235ceb7c that should be an improvement on the previous method performance wise and seems to have resolved the issue.
