### ISSUE TITLE
Search filters should reset with each new search

### ISSUE THREAD

**Issue by chrismplus** [mplusmuseum/mplusmuseum-stories#99]
**Use-case:** 
1. I enter the search term "Hong Kong" (https://plus.zakgroup.co.uk/en/search?q=hong%20kong)
2. Results are returned. 
3. I filter by blog posts.  
4. I enter a new search term, "exhibitions".
5. The search results are still filtered by "blog posts", meaning I miss out on Podium articles.

**Comment by rdunk** [comment]
Agreed, will implement this.

**Comment by rdunk** [comment]
Implemented in d936aaa6d06d16a84866067f4481d7e830eda8e3.
